/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : AdId,
  'websiteLink' : string,
  'clicks' : bigint,
  'endDate' : Timestamp,
  'imageAssetId' : string,
  'views' : bigint,
  'createdAt' : Timestamp,
  'langText' : AdLangText,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'adText' : string,
  'adType' : AdType,
  'companyName' : string,
  'contactNumber' : string,
  'startDate' : Timestamp,
}
export type AdId = bigint;
export interface AdLangText {
  'en' : string,
  'hi' : string,
  'kn' : string,
  'mr' : string,
}
export type AdType = { 'both' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'author' : string,
  'updatedAt' : Timestamp,
}
export type AnnouncementId = bigint;
export interface AnnouncementInput {
  'title' : string,
  'content' : string,
  'author' : string,
}
export interface AshtakootResult {
  'total' : bigint,
  'varna' : bigint,
  'gana' : bigint,
  'nadi' : bigint,
  'tara' : bigint,
  'grahaMaitri' : bigint,
  'yoni' : bigint,
  'vashya' : bigint,
  'bhakoot' : bigint,
}
export interface ChatConversationSummary {
  'userId' : [] | [MemberId],
  'lastActivity' : Timestamp,
  'messageCount' : bigint,
  'sessionId' : string,
  'firstMessage' : string,
}
export interface ChatMessage {
  'id' : ChatMessageId,
  'userId' : [] | [MemberId],
  'createdAt' : Timestamp,
  'language' : string,
  'message' : string,
  'sessionId' : string,
  'isBot' : boolean,
}
export type ChatMessageId = bigint;
export interface ConversationSummary {
  'otherMemberName' : string,
  'otherMemberId' : MemberId,
  'lastMessageAt' : Timestamp,
  'lastMessage' : string,
  'unreadCount' : bigint,
}
export interface CreateAdInput {
  'websiteLink' : string,
  'endDate' : Timestamp,
  'imageAssetId' : string,
  'langText' : AdLangText,
  'imageUrl' : string,
  'adText' : string,
  'adType' : AdType,
  'companyName' : string,
  'contactNumber' : string,
  'startDate' : Timestamp,
}
export type FamilyType = { 'Extended' : null } |
  { 'Nuclear' : null } |
  { 'Joint' : null };
export type Gender = { 'Male' : null } |
  { 'Female' : null };
export interface KundaliResult {
  'nakshatra1Name' : string,
  'verdict' : string,
  'score' : AshtakootResult,
  'nakshatra2Name' : string,
  'rashi1' : bigint,
  'rashi2' : bigint,
  'charan1' : bigint,
  'charan2' : bigint,
  'nakshatra1' : bigint,
  'nakshatra2' : bigint,
}
export interface Member {
  'id' : MemberId,
  'age' : bigint,
  'occupation' : string,
  'familyType' : FamilyType,
  'paymentStatus' : PaymentStatus,
  'nativePlace' : string,
  'heightCm' : bigint,
  'birthTime' : [] | [string],
  'owner' : Principal,
  'dateOfBirth' : string,
  'city' : string,
  'motherOccupation' : string,
  'name' : string,
  'annualIncomeINR' : bigint,
  'createdAt' : Timestamp,
  'education' : string,
  'birthPlaceLat' : [] | [number],
  'birthPlaceLng' : [] | [number],
  'photoModerationStatus' : PhotoModerationStatus,
  'birthPlace' : [] | [string],
  'mobileNumber' : [] | [string],
  'photoUrl' : string,
  'siblingsCount' : bigint,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'upjati' : [] | [string],
  'paymentScreenshotUrl' : [] | [string],
  'isVerified' : boolean,
  'paymentUpiRef' : [] | [string],
  'gender' : Gender,
  'partnerPreferences' : PartnerPreferences,
  'fatherOccupation' : string,
  'membership' : MembershipTier,
  'charan' : [] | [bigint],
  'profileViews' : bigint,
  'nakshatra' : [] | [bigint],
  'rashi' : [] | [bigint],
  'photoAssetId' : [] | [string],
}
export interface MemberAdminSummary {
  'id' : MemberId,
  'paymentStatus' : PaymentStatus,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'hasPhoto' : boolean,
  'photoModerationStatus' : PhotoModerationStatus,
  'isProfileComplete' : boolean,
  'isActive' : boolean,
  'isVerified' : boolean,
  'gender' : Gender,
  'membership' : MembershipTier,
}
export type MemberId = bigint;
export interface MemberInput {
  'age' : bigint,
  'occupation' : string,
  'familyType' : FamilyType,
  'nativePlace' : string,
  'heightCm' : bigint,
  'birthTime' : [] | [string],
  'dateOfBirth' : string,
  'city' : string,
  'motherOccupation' : string,
  'name' : string,
  'annualIncomeINR' : bigint,
  'education' : string,
  'birthPlaceLat' : [] | [number],
  'birthPlaceLng' : [] | [number],
  'birthPlace' : [] | [string],
  'mobileNumber' : [] | [string],
  'photoUrl' : string,
  'siblingsCount' : bigint,
  'upjati' : [] | [string],
  'gender' : Gender,
  'partnerPreferences' : PartnerPreferences,
  'fatherOccupation' : string,
}
export type MembershipTier = { 'Premium' : null } |
  { 'Free' : null };
export interface Message {
  'id' : MessageId,
  'isDeleted' : boolean,
  'content' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'receiverId' : MemberId,
  'senderId' : MemberId,
}
export type MessageId = bigint;
export interface NakshatraData {
  'charan' : bigint,
  'nakshatra' : bigint,
  'rashi' : bigint,
  'moonLongitude' : number,
}
export interface PartnerPreferences {
  'maxHeight' : [] | [bigint],
  'preferredOccupation' : Array<string>,
  'minAge' : [] | [bigint],
  'preferredEducation' : Array<string>,
  'minHeight' : [] | [bigint],
  'preferredUpjati' : Array<string>,
  'maxAge' : [] | [bigint],
  'maxIncome' : [] | [bigint],
  'preferredLocations' : Array<string>,
  'minIncome' : [] | [bigint],
}
export interface PaymentConfigPublic {
  'qrImageUrl' : string,
  'updatedAt' : Timestamp,
  'upiId' : string,
  'qrImageAssetId' : string,
}
export type PaymentStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Uploaded' : null } |
  { 'Pending' : null };
export interface PhotoModerationInfo {
  'memberId' : MemberId,
  'photoModerationStatus' : PhotoModerationStatus,
  'memberName' : string,
  'photoAssetId' : string,
}
export type PhotoModerationStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface SearchFilter {
  'occupation' : [] | [string],
  'city' : [] | [string],
  'education' : [] | [string],
  'minAge' : [] | [bigint],
  'upjati' : [] | [string],
  'gender' : [] | [Gender],
  'maxAge' : [] | [bigint],
  'maxIncome' : [] | [bigint],
  'minIncome' : [] | [bigint],
}
export interface SmsConfig {
  'provider' : SmsProvider,
  'templateId' : [] | [string],
  'enabled' : boolean,
  'apiKey' : string,
  'senderName' : string,
}
export interface SmsOtpLogEntry {
  'provider' : string,
  'errorCode' : [] | [string],
  'timestamp' : Timestamp,
  'success' : boolean,
  'phone' : string,
}
export type SmsProvider = { 'Fast2SMS' : null } |
  { 'Custom' : null } |
  { 'MSG91' : null };
export interface Stats {
  'successfulMarriages' : bigint,
  'premiumMembers' : bigint,
  'totalMembers' : bigint,
  'activeMembers' : bigint,
}
export type StoryId = bigint;
export interface SuccessStory {
  'id' : StoryId,
  'featured' : boolean,
  'marriageDate' : string,
  'createdAt' : Timestamp,
  'photoUrl' : string,
  'updatedAt' : Timestamp,
  'brideName' : string,
  'groomName' : string,
  'testimonial' : string,
}
export interface SuccessStoryInput {
  'featured' : boolean,
  'marriageDate' : string,
  'photoUrl' : string,
  'brideName' : string,
  'groomName' : string,
  'testimonial' : string,
}
export type Timestamp = bigint;
export interface UpdateAdInput {
  'id' : AdId,
  'websiteLink' : string,
  'endDate' : Timestamp,
  'imageAssetId' : string,
  'langText' : AdLangText,
  'isActive' : boolean,
  'imageUrl' : string,
  'adText' : string,
  'adType' : AdType,
  'companyName' : string,
  'contactNumber' : string,
  'startDate' : Timestamp,
}
export interface _SERVICE {
  'adminApproveMember' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApprovePayment' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveProfilePhoto' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminBlockMember' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminCreateAd' : ActorMethod<[CreateAdInput], Ad>,
  'adminCreateAnnouncement' : ActorMethod<[AnnouncementInput], AnnouncementId>,
  'adminCreateSuccessStory' : ActorMethod<[SuccessStoryInput], StoryId>,
  'adminDeleteAd' : ActorMethod<[AdId], boolean>,
  'adminDeleteAnnouncement' : ActorMethod<[AnnouncementId], boolean>,
  'adminDeleteMember' : ActorMethod<[MemberId], boolean>,
  'adminDeleteMemberPhoto' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteMessage' : ActorMethod<
    [MessageId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteProfile' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteSuccessStory' : ActorMethod<[StoryId], boolean>,
  'adminGetAllChatConversations' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'conversations' : Array<ChatConversationSummary> }
  >,
  'adminGetChatSession' : ActorMethod<[string], Array<ChatMessage>>,
  'adminGetConversation' : ActorMethod<
    [MemberId, MemberId, bigint, bigint],
    Array<Message>
  >,
  'adminGetCredentialInfo' : ActorMethod<
    [],
    { 'adminMobile' : string, 'username' : string, 'isLocked' : boolean }
  >,
  'adminGetPaymentConfig' : ActorMethod<[], PaymentConfigPublic>,
  'adminGetSmsConfig' : ActorMethod<[], [] | [SmsConfig]>,
  'adminGetSmsOtpLogs' : ActorMethod<[], Array<SmsOtpLogEntry>>,
  'adminGetStats' : ActorMethod<[], Stats>,
  'adminListAllAds' : ActorMethod<[], Array<Ad>>,
  'adminListAllMembers' : ActorMethod<[], Array<Member>>,
  'adminListAllPhotos' : ActorMethod<[], Array<PhotoModerationInfo>>,
  'adminLogin_Step1_CheckPassword' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'invalid' : null } |
      { 'locked' : string }
  >,
  'adminLogin_Step2_VerifyOtp' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'expired' : null } |
      { 'invalid' : null }
  >,
  'adminMuteConversation' : ActorMethod<
    [MemberId, MemberId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectMember' : ActorMethod<
    [MemberId, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectPayment' : ActorMethod<
    [MemberId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectProfilePhoto' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSearchMembers' : ActorMethod<[string], Array<Member>>,
  'adminSetAdmin' : ActorMethod<[Principal], boolean>,
  'adminSetMemberActive' : ActorMethod<[MemberId, boolean], boolean>,
  'adminSetPaymentConfig' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetSmsConfig' : ActorMethod<
    [SmsConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminTestSms' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminToggleAdActive' : ActorMethod<[AdId], [] | [Ad]>,
  'adminUnverifyProfile' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateAd' : ActorMethod<[UpdateAdInput], [] | [Ad]>,
  'adminUpdateAnnouncement' : ActorMethod<
    [AnnouncementId, AnnouncementInput],
    boolean
  >,
  'adminUpdateCredentials' : ActorMethod<
    [[] | [string], [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateSuccessStory' : ActorMethod<
    [StoryId, SuccessStoryInput],
    boolean
  >,
  'adminVerifyProfile' : ActorMethod<
    [MemberId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'computeKundaliMilan' : ActorMethod<[string, string], [] | [KundaliResult]>,
  'computeKundaliScore' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
    ],
    [] | [KundaliResult]
  >,
  'computePreciseNakshatra' : ActorMethod<
    [string, string, number, number],
    [] | [NakshatraData]
  >,
  'createProfile' : ActorMethod<[MemberInput], MemberId>,
  'deleteProfile' : ActorMethod<[], boolean>,
  'getActiveAds' : ActorMethod<[], Array<Ad>>,
  'getAnnouncement' : ActorMethod<[AnnouncementId], [] | [Announcement]>,
  'getChatGreeting' : ActorMethod<[string], string>,
  'getChatHistory' : ActorMethod<[string], Array<ChatMessage>>,
  'getConversation' : ActorMethod<[MemberId, bigint, bigint], Array<Message>>,
  'getDailyMessageCount' : ActorMethod<[], bigint>,
  'getMemberProfile' : ActorMethod<[MemberId], [] | [Member]>,
  'getMyConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getMyMatches' : ActorMethod<[], Array<Member>>,
  'getMyProfile' : ActorMethod<[], [] | [Member]>,
  'getNakshatraForDob' : ActorMethod<[string], [] | [bigint]>,
  'getNakshatraName' : ActorMethod<[bigint], string>,
  'getNearbyMatches' : ActorMethod<[], Array<Member>>,
  'getProfilePhotoUploadUrl' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getStats' : ActorMethod<[], Stats>,
  'getSuccessStory' : ActorMethod<[StoryId], [] | [SuccessStory]>,
  'getTodaysMatches' : ActorMethod<[], Array<Member>>,
  'listAllMembers' : ActorMethod<[], Array<MemberAdminSummary>>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listFeaturedStories' : ActorMethod<[], Array<SuccessStory>>,
  'listPendingPayments' : ActorMethod<[], Array<Member>>,
  'listPremiumProfiles' : ActorMethod<[], Array<Member>>,
  'listProfiles' : ActorMethod<[bigint, bigint], Array<Member>>,
  'listSuccessStories' : ActorMethod<[], Array<SuccessStory>>,
  'markAsRead' : ActorMethod<[MemberId], { 'ok' : null } | { 'err' : string }>,
  'recordAdClick' : ActorMethod<[AdId], undefined>,
  'recordAdView' : ActorMethod<[AdId], undefined>,
  'searchProfiles' : ActorMethod<[SearchFilter], Array<Member>>,
  'sendChatMessage' : ActorMethod<[string, string, string], string>,
  'sendMessage' : ActorMethod<
    [MemberId, string],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'sendOtp' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'submitPaymentScreenshot' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMemberNakshatra' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePaymentStatus' : ActorMethod<
    [MemberId, PaymentStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<[MemberInput], boolean>,
  'updateProfilePhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'upgradeToPremium' : ActorMethod<[], boolean>,
  'verifyOtp' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];