/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MemberId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AdLangText = IDL.Record({
  'en' : IDL.Text,
  'hi' : IDL.Text,
  'kn' : IDL.Text,
  'mr' : IDL.Text,
});
export const AdType = IDL.Variant({
  'both' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const CreateAdInput = IDL.Record({
  'websiteLink' : IDL.Text,
  'endDate' : Timestamp,
  'imageAssetId' : IDL.Text,
  'langText' : AdLangText,
  'imageUrl' : IDL.Text,
  'adText' : IDL.Text,
  'adType' : AdType,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'startDate' : Timestamp,
});
export const AdId = IDL.Nat;
export const Ad = IDL.Record({
  'id' : AdId,
  'websiteLink' : IDL.Text,
  'clicks' : IDL.Nat,
  'endDate' : Timestamp,
  'imageAssetId' : IDL.Text,
  'views' : IDL.Nat,
  'createdAt' : Timestamp,
  'langText' : AdLangText,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'adText' : IDL.Text,
  'adType' : AdType,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'startDate' : Timestamp,
});
export const AnnouncementInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const AnnouncementId = IDL.Nat;
export const SuccessStoryInput = IDL.Record({
  'featured' : IDL.Bool,
  'marriageDate' : IDL.Text,
  'photoUrl' : IDL.Text,
  'brideName' : IDL.Text,
  'groomName' : IDL.Text,
  'testimonial' : IDL.Text,
});
export const StoryId = IDL.Nat;
export const MessageId = IDL.Nat;
export const ChatConversationSummary = IDL.Record({
  'userId' : IDL.Opt(MemberId),
  'lastActivity' : Timestamp,
  'messageCount' : IDL.Nat,
  'sessionId' : IDL.Text,
  'firstMessage' : IDL.Text,
});
export const ChatMessageId = IDL.Nat;
export const ChatMessage = IDL.Record({
  'id' : ChatMessageId,
  'userId' : IDL.Opt(MemberId),
  'createdAt' : Timestamp,
  'language' : IDL.Text,
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
  'isBot' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'receiverId' : MemberId,
  'senderId' : MemberId,
});
export const PaymentConfigPublic = IDL.Record({
  'qrImageUrl' : IDL.Text,
  'updatedAt' : Timestamp,
  'upiId' : IDL.Text,
  'qrImageAssetId' : IDL.Text,
});
export const SmsProvider = IDL.Variant({
  'Fast2SMS' : IDL.Null,
  'Custom' : IDL.Null,
  'MSG91' : IDL.Null,
});
export const SmsConfig = IDL.Record({
  'provider' : SmsProvider,
  'templateId' : IDL.Opt(IDL.Text),
  'enabled' : IDL.Bool,
  'apiKey' : IDL.Text,
  'senderName' : IDL.Text,
});
export const SmsOtpLogEntry = IDL.Record({
  'provider' : IDL.Text,
  'errorCode' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'success' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Stats = IDL.Record({
  'successfulMarriages' : IDL.Nat,
  'premiumMembers' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'activeMembers' : IDL.Nat,
});
export const FamilyType = IDL.Variant({
  'Extended' : IDL.Null,
  'Nuclear' : IDL.Null,
  'Joint' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Uploaded' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PhotoModerationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Gender = IDL.Variant({ 'Male' : IDL.Null, 'Female' : IDL.Null });
export const PartnerPreferences = IDL.Record({
  'maxHeight' : IDL.Opt(IDL.Nat),
  'preferredOccupation' : IDL.Vec(IDL.Text),
  'minAge' : IDL.Opt(IDL.Nat),
  'preferredEducation' : IDL.Vec(IDL.Text),
  'minHeight' : IDL.Opt(IDL.Nat),
  'preferredUpjati' : IDL.Vec(IDL.Text),
  'maxAge' : IDL.Opt(IDL.Nat),
  'maxIncome' : IDL.Opt(IDL.Nat),
  'preferredLocations' : IDL.Vec(IDL.Text),
  'minIncome' : IDL.Opt(IDL.Nat),
});
export const MembershipTier = IDL.Variant({
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : MemberId,
  'age' : IDL.Nat,
  'occupation' : IDL.Text,
  'familyType' : FamilyType,
  'paymentStatus' : PaymentStatus,
  'nativePlace' : IDL.Text,
  'heightCm' : IDL.Nat,
  'birthTime' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'dateOfBirth' : IDL.Text,
  'city' : IDL.Text,
  'motherOccupation' : IDL.Text,
  'name' : IDL.Text,
  'annualIncomeINR' : IDL.Nat,
  'createdAt' : Timestamp,
  'education' : IDL.Text,
  'birthPlaceLat' : IDL.Opt(IDL.Float64),
  'birthPlaceLng' : IDL.Opt(IDL.Float64),
  'photoModerationStatus' : PhotoModerationStatus,
  'birthPlace' : IDL.Opt(IDL.Text),
  'mobileNumber' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Text,
  'siblingsCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'upjati' : IDL.Opt(IDL.Text),
  'paymentScreenshotUrl' : IDL.Opt(IDL.Text),
  'isVerified' : IDL.Bool,
  'paymentUpiRef' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'partnerPreferences' : PartnerPreferences,
  'fatherOccupation' : IDL.Text,
  'membership' : MembershipTier,
  'charan' : IDL.Opt(IDL.Nat),
  'profileViews' : IDL.Nat,
  'nakshatra' : IDL.Opt(IDL.Nat),
  'rashi' : IDL.Opt(IDL.Nat),
  'photoAssetId' : IDL.Opt(IDL.Text),
});
export const PhotoModerationInfo = IDL.Record({
  'memberId' : MemberId,
  'photoModerationStatus' : PhotoModerationStatus,
  'memberName' : IDL.Text,
  'photoAssetId' : IDL.Text,
});
export const UpdateAdInput = IDL.Record({
  'id' : AdId,
  'websiteLink' : IDL.Text,
  'endDate' : Timestamp,
  'imageAssetId' : IDL.Text,
  'langText' : AdLangText,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'adText' : IDL.Text,
  'adType' : AdType,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'startDate' : Timestamp,
});
export const AshtakootResult = IDL.Record({
  'total' : IDL.Nat,
  'varna' : IDL.Nat,
  'gana' : IDL.Nat,
  'nadi' : IDL.Nat,
  'tara' : IDL.Nat,
  'grahaMaitri' : IDL.Nat,
  'yoni' : IDL.Nat,
  'vashya' : IDL.Nat,
  'bhakoot' : IDL.Nat,
});
export const KundaliResult = IDL.Record({
  'nakshatra1Name' : IDL.Text,
  'verdict' : IDL.Text,
  'score' : AshtakootResult,
  'nakshatra2Name' : IDL.Text,
  'rashi1' : IDL.Nat,
  'rashi2' : IDL.Nat,
  'charan1' : IDL.Nat,
  'charan2' : IDL.Nat,
  'nakshatra1' : IDL.Nat,
  'nakshatra2' : IDL.Nat,
});
export const NakshatraData = IDL.Record({
  'charan' : IDL.Nat,
  'nakshatra' : IDL.Nat,
  'rashi' : IDL.Nat,
  'moonLongitude' : IDL.Float64,
});
export const MemberInput = IDL.Record({
  'age' : IDL.Nat,
  'occupation' : IDL.Text,
  'familyType' : FamilyType,
  'nativePlace' : IDL.Text,
  'heightCm' : IDL.Nat,
  'birthTime' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'city' : IDL.Text,
  'motherOccupation' : IDL.Text,
  'name' : IDL.Text,
  'annualIncomeINR' : IDL.Nat,
  'education' : IDL.Text,
  'birthPlaceLat' : IDL.Opt(IDL.Float64),
  'birthPlaceLng' : IDL.Opt(IDL.Float64),
  'birthPlace' : IDL.Opt(IDL.Text),
  'mobileNumber' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Text,
  'siblingsCount' : IDL.Nat,
  'upjati' : IDL.Opt(IDL.Text),
  'gender' : Gender,
  'partnerPreferences' : PartnerPreferences,
  'fatherOccupation' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'author' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'otherMemberName' : IDL.Text,
  'otherMemberId' : MemberId,
  'lastMessageAt' : Timestamp,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
});
export const SuccessStory = IDL.Record({
  'id' : StoryId,
  'featured' : IDL.Bool,
  'marriageDate' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Text,
  'updatedAt' : Timestamp,
  'brideName' : IDL.Text,
  'groomName' : IDL.Text,
  'testimonial' : IDL.Text,
});
export const MemberAdminSummary = IDL.Record({
  'id' : MemberId,
  'paymentStatus' : PaymentStatus,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'hasPhoto' : IDL.Bool,
  'photoModerationStatus' : PhotoModerationStatus,
  'isProfileComplete' : IDL.Bool,
  'isActive' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'gender' : Gender,
  'membership' : MembershipTier,
});
export const SearchFilter = IDL.Record({
  'occupation' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'education' : IDL.Opt(IDL.Text),
  'minAge' : IDL.Opt(IDL.Nat),
  'upjati' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'maxAge' : IDL.Opt(IDL.Nat),
  'maxIncome' : IDL.Opt(IDL.Nat),
  'minIncome' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'adminApproveMember' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApprovePayment' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveProfilePhoto' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminBlockMember' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateAd' : IDL.Func([CreateAdInput], [Ad], []),
  'adminCreateAnnouncement' : IDL.Func(
      [AnnouncementInput],
      [AnnouncementId],
      [],
    ),
  'adminCreateSuccessStory' : IDL.Func([SuccessStoryInput], [StoryId], []),
  'adminDeleteAd' : IDL.Func([AdId], [IDL.Bool], []),
  'adminDeleteAnnouncement' : IDL.Func([AnnouncementId], [IDL.Bool], []),
  'adminDeleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
  'adminDeleteMemberPhoto' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteMessage' : IDL.Func(
      [MessageId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteProfile' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteSuccessStory' : IDL.Func([StoryId], [IDL.Bool], []),
  'adminGetAllChatConversations' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'conversations' : IDL.Vec(ChatConversationSummary),
        }),
      ],
      ['query'],
    ),
  'adminGetChatSession' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'adminGetConversation' : IDL.Func(
      [MemberId, MemberId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'adminGetCredentialInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'adminMobile' : IDL.Text,
          'username' : IDL.Text,
          'isLocked' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'adminGetPaymentConfig' : IDL.Func([], [PaymentConfigPublic], ['query']),
  'adminGetSmsConfig' : IDL.Func([], [IDL.Opt(SmsConfig)], ['query']),
  'adminGetSmsOtpLogs' : IDL.Func([], [IDL.Vec(SmsOtpLogEntry)], ['query']),
  'adminGetStats' : IDL.Func([], [Stats], ['query']),
  'adminListAllAds' : IDL.Func([], [IDL.Vec(Ad)], []),
  'adminListAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'adminListAllPhotos' : IDL.Func(
      [],
      [IDL.Vec(PhotoModerationInfo)],
      ['query'],
    ),
  'adminLogin_Step1_CheckPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Text,
          'invalid' : IDL.Null,
          'locked' : IDL.Text,
        }),
      ],
      [],
    ),
  'adminLogin_Step2_VerifyOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'expired' : IDL.Null,
          'invalid' : IDL.Null,
        }),
      ],
      [],
    ),
  'adminMuteConversation' : IDL.Func(
      [MemberId, MemberId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectMember' : IDL.Func(
      [MemberId, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectPayment' : IDL.Func(
      [MemberId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectProfilePhoto' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSearchMembers' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
  'adminSetAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'adminSetMemberActive' : IDL.Func([MemberId, IDL.Bool], [IDL.Bool], []),
  'adminSetPaymentConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetSmsConfig' : IDL.Func(
      [SmsConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminTestSms' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleAdActive' : IDL.Func([AdId], [IDL.Opt(Ad)], []),
  'adminUnverifyProfile' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateAd' : IDL.Func([UpdateAdInput], [IDL.Opt(Ad)], []),
  'adminUpdateAnnouncement' : IDL.Func(
      [AnnouncementId, AnnouncementInput],
      [IDL.Bool],
      [],
    ),
  'adminUpdateCredentials' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateSuccessStory' : IDL.Func(
      [StoryId, SuccessStoryInput],
      [IDL.Bool],
      [],
    ),
  'adminVerifyProfile' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'computeKundaliMilan' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(KundaliResult)],
      ['query'],
    ),
  'computeKundaliScore' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Opt(KundaliResult)],
      ['query'],
    ),
  'computePreciseNakshatra' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Opt(NakshatraData)],
      ['query'],
    ),
  'createProfile' : IDL.Func([MemberInput], [MemberId], []),
  'deleteProfile' : IDL.Func([], [IDL.Bool], []),
  'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAnnouncement' : IDL.Func(
      [AnnouncementId],
      [IDL.Opt(Announcement)],
      ['query'],
    ),
  'getChatGreeting' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getConversation' : IDL.Func(
      [MemberId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getDailyMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMemberProfile' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
  'getMyConversations' : IDL.Func(
      [],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getMyMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
  'getNakshatraForDob' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getNakshatraName' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getNearbyMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getProfilePhotoUploadUrl' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getSuccessStory' : IDL.Func([StoryId], [IDL.Opt(SuccessStory)], ['query']),
  'getTodaysMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'listAllMembers' : IDL.Func([], [IDL.Vec(MemberAdminSummary)], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listFeaturedStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'listPendingPayments' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'listPremiumProfiles' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Member)], ['query']),
  'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'markAsRead' : IDL.Func(
      [MemberId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordAdClick' : IDL.Func([AdId], [], []),
  'recordAdView' : IDL.Func([AdId], [], []),
  'searchProfiles' : IDL.Func([SearchFilter], [IDL.Vec(Member)], ['query']),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'sendMessage' : IDL.Func(
      [MemberId, IDL.Text],
      [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
      [],
    ),
  'sendOtp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitPaymentScreenshot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMemberNakshatra' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [MemberId, PaymentStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func([MemberInput], [IDL.Bool], []),
  'updateProfilePhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
  'verifyOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MemberId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AdLangText = IDL.Record({
    'en' : IDL.Text,
    'hi' : IDL.Text,
    'kn' : IDL.Text,
    'mr' : IDL.Text,
  });
  const AdType = IDL.Variant({
    'both' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const CreateAdInput = IDL.Record({
    'websiteLink' : IDL.Text,
    'endDate' : Timestamp,
    'imageAssetId' : IDL.Text,
    'langText' : AdLangText,
    'imageUrl' : IDL.Text,
    'adText' : IDL.Text,
    'adType' : AdType,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'startDate' : Timestamp,
  });
  const AdId = IDL.Nat;
  const Ad = IDL.Record({
    'id' : AdId,
    'websiteLink' : IDL.Text,
    'clicks' : IDL.Nat,
    'endDate' : Timestamp,
    'imageAssetId' : IDL.Text,
    'views' : IDL.Nat,
    'createdAt' : Timestamp,
    'langText' : AdLangText,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'adText' : IDL.Text,
    'adType' : AdType,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'startDate' : Timestamp,
  });
  const AnnouncementInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const AnnouncementId = IDL.Nat;
  const SuccessStoryInput = IDL.Record({
    'featured' : IDL.Bool,
    'marriageDate' : IDL.Text,
    'photoUrl' : IDL.Text,
    'brideName' : IDL.Text,
    'groomName' : IDL.Text,
    'testimonial' : IDL.Text,
  });
  const StoryId = IDL.Nat;
  const MessageId = IDL.Nat;
  const ChatConversationSummary = IDL.Record({
    'userId' : IDL.Opt(MemberId),
    'lastActivity' : Timestamp,
    'messageCount' : IDL.Nat,
    'sessionId' : IDL.Text,
    'firstMessage' : IDL.Text,
  });
  const ChatMessageId = IDL.Nat;
  const ChatMessage = IDL.Record({
    'id' : ChatMessageId,
    'userId' : IDL.Opt(MemberId),
    'createdAt' : Timestamp,
    'language' : IDL.Text,
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
    'isBot' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'receiverId' : MemberId,
    'senderId' : MemberId,
  });
  const PaymentConfigPublic = IDL.Record({
    'qrImageUrl' : IDL.Text,
    'updatedAt' : Timestamp,
    'upiId' : IDL.Text,
    'qrImageAssetId' : IDL.Text,
  });
  const SmsProvider = IDL.Variant({
    'Fast2SMS' : IDL.Null,
    'Custom' : IDL.Null,
    'MSG91' : IDL.Null,
  });
  const SmsConfig = IDL.Record({
    'provider' : SmsProvider,
    'templateId' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
    'apiKey' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const SmsOtpLogEntry = IDL.Record({
    'provider' : IDL.Text,
    'errorCode' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'success' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'successfulMarriages' : IDL.Nat,
    'premiumMembers' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'activeMembers' : IDL.Nat,
  });
  const FamilyType = IDL.Variant({
    'Extended' : IDL.Null,
    'Nuclear' : IDL.Null,
    'Joint' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Uploaded' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PhotoModerationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'Male' : IDL.Null, 'Female' : IDL.Null });
  const PartnerPreferences = IDL.Record({
    'maxHeight' : IDL.Opt(IDL.Nat),
    'preferredOccupation' : IDL.Vec(IDL.Text),
    'minAge' : IDL.Opt(IDL.Nat),
    'preferredEducation' : IDL.Vec(IDL.Text),
    'minHeight' : IDL.Opt(IDL.Nat),
    'preferredUpjati' : IDL.Vec(IDL.Text),
    'maxAge' : IDL.Opt(IDL.Nat),
    'maxIncome' : IDL.Opt(IDL.Nat),
    'preferredLocations' : IDL.Vec(IDL.Text),
    'minIncome' : IDL.Opt(IDL.Nat),
  });
  const MembershipTier = IDL.Variant({
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : MemberId,
    'age' : IDL.Nat,
    'occupation' : IDL.Text,
    'familyType' : FamilyType,
    'paymentStatus' : PaymentStatus,
    'nativePlace' : IDL.Text,
    'heightCm' : IDL.Nat,
    'birthTime' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'dateOfBirth' : IDL.Text,
    'city' : IDL.Text,
    'motherOccupation' : IDL.Text,
    'name' : IDL.Text,
    'annualIncomeINR' : IDL.Nat,
    'createdAt' : Timestamp,
    'education' : IDL.Text,
    'birthPlaceLat' : IDL.Opt(IDL.Float64),
    'birthPlaceLng' : IDL.Opt(IDL.Float64),
    'photoModerationStatus' : PhotoModerationStatus,
    'birthPlace' : IDL.Opt(IDL.Text),
    'mobileNumber' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Text,
    'siblingsCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'upjati' : IDL.Opt(IDL.Text),
    'paymentScreenshotUrl' : IDL.Opt(IDL.Text),
    'isVerified' : IDL.Bool,
    'paymentUpiRef' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'partnerPreferences' : PartnerPreferences,
    'fatherOccupation' : IDL.Text,
    'membership' : MembershipTier,
    'charan' : IDL.Opt(IDL.Nat),
    'profileViews' : IDL.Nat,
    'nakshatra' : IDL.Opt(IDL.Nat),
    'rashi' : IDL.Opt(IDL.Nat),
    'photoAssetId' : IDL.Opt(IDL.Text),
  });
  const PhotoModerationInfo = IDL.Record({
    'memberId' : MemberId,
    'photoModerationStatus' : PhotoModerationStatus,
    'memberName' : IDL.Text,
    'photoAssetId' : IDL.Text,
  });
  const UpdateAdInput = IDL.Record({
    'id' : AdId,
    'websiteLink' : IDL.Text,
    'endDate' : Timestamp,
    'imageAssetId' : IDL.Text,
    'langText' : AdLangText,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'adText' : IDL.Text,
    'adType' : AdType,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'startDate' : Timestamp,
  });
  const AshtakootResult = IDL.Record({
    'total' : IDL.Nat,
    'varna' : IDL.Nat,
    'gana' : IDL.Nat,
    'nadi' : IDL.Nat,
    'tara' : IDL.Nat,
    'grahaMaitri' : IDL.Nat,
    'yoni' : IDL.Nat,
    'vashya' : IDL.Nat,
    'bhakoot' : IDL.Nat,
  });
  const KundaliResult = IDL.Record({
    'nakshatra1Name' : IDL.Text,
    'verdict' : IDL.Text,
    'score' : AshtakootResult,
    'nakshatra2Name' : IDL.Text,
    'rashi1' : IDL.Nat,
    'rashi2' : IDL.Nat,
    'charan1' : IDL.Nat,
    'charan2' : IDL.Nat,
    'nakshatra1' : IDL.Nat,
    'nakshatra2' : IDL.Nat,
  });
  const NakshatraData = IDL.Record({
    'charan' : IDL.Nat,
    'nakshatra' : IDL.Nat,
    'rashi' : IDL.Nat,
    'moonLongitude' : IDL.Float64,
  });
  const MemberInput = IDL.Record({
    'age' : IDL.Nat,
    'occupation' : IDL.Text,
    'familyType' : FamilyType,
    'nativePlace' : IDL.Text,
    'heightCm' : IDL.Nat,
    'birthTime' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'city' : IDL.Text,
    'motherOccupation' : IDL.Text,
    'name' : IDL.Text,
    'annualIncomeINR' : IDL.Nat,
    'education' : IDL.Text,
    'birthPlaceLat' : IDL.Opt(IDL.Float64),
    'birthPlaceLng' : IDL.Opt(IDL.Float64),
    'birthPlace' : IDL.Opt(IDL.Text),
    'mobileNumber' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Text,
    'siblingsCount' : IDL.Nat,
    'upjati' : IDL.Opt(IDL.Text),
    'gender' : Gender,
    'partnerPreferences' : PartnerPreferences,
    'fatherOccupation' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'author' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'otherMemberName' : IDL.Text,
    'otherMemberId' : MemberId,
    'lastMessageAt' : Timestamp,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
  });
  const SuccessStory = IDL.Record({
    'id' : StoryId,
    'featured' : IDL.Bool,
    'marriageDate' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Text,
    'updatedAt' : Timestamp,
    'brideName' : IDL.Text,
    'groomName' : IDL.Text,
    'testimonial' : IDL.Text,
  });
  const MemberAdminSummary = IDL.Record({
    'id' : MemberId,
    'paymentStatus' : PaymentStatus,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'hasPhoto' : IDL.Bool,
    'photoModerationStatus' : PhotoModerationStatus,
    'isProfileComplete' : IDL.Bool,
    'isActive' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'gender' : Gender,
    'membership' : MembershipTier,
  });
  const SearchFilter = IDL.Record({
    'occupation' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'education' : IDL.Opt(IDL.Text),
    'minAge' : IDL.Opt(IDL.Nat),
    'upjati' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'maxAge' : IDL.Opt(IDL.Nat),
    'maxIncome' : IDL.Opt(IDL.Nat),
    'minIncome' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'adminApproveMember' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApprovePayment' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveProfilePhoto' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminBlockMember' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateAd' : IDL.Func([CreateAdInput], [Ad], []),
    'adminCreateAnnouncement' : IDL.Func(
        [AnnouncementInput],
        [AnnouncementId],
        [],
      ),
    'adminCreateSuccessStory' : IDL.Func([SuccessStoryInput], [StoryId], []),
    'adminDeleteAd' : IDL.Func([AdId], [IDL.Bool], []),
    'adminDeleteAnnouncement' : IDL.Func([AnnouncementId], [IDL.Bool], []),
    'adminDeleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
    'adminDeleteMemberPhoto' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteMessage' : IDL.Func(
        [MessageId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteProfile' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteSuccessStory' : IDL.Func([StoryId], [IDL.Bool], []),
    'adminGetAllChatConversations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'conversations' : IDL.Vec(ChatConversationSummary),
          }),
        ],
        ['query'],
      ),
    'adminGetChatSession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'adminGetConversation' : IDL.Func(
        [MemberId, MemberId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'adminGetCredentialInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'adminMobile' : IDL.Text,
            'username' : IDL.Text,
            'isLocked' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'adminGetPaymentConfig' : IDL.Func([], [PaymentConfigPublic], ['query']),
    'adminGetSmsConfig' : IDL.Func([], [IDL.Opt(SmsConfig)], ['query']),
    'adminGetSmsOtpLogs' : IDL.Func([], [IDL.Vec(SmsOtpLogEntry)], ['query']),
    'adminGetStats' : IDL.Func([], [Stats], ['query']),
    'adminListAllAds' : IDL.Func([], [IDL.Vec(Ad)], []),
    'adminListAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'adminListAllPhotos' : IDL.Func(
        [],
        [IDL.Vec(PhotoModerationInfo)],
        ['query'],
      ),
    'adminLogin_Step1_CheckPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Text,
            'invalid' : IDL.Null,
            'locked' : IDL.Text,
          }),
        ],
        [],
      ),
    'adminLogin_Step2_VerifyOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'expired' : IDL.Null,
            'invalid' : IDL.Null,
          }),
        ],
        [],
      ),
    'adminMuteConversation' : IDL.Func(
        [MemberId, MemberId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectMember' : IDL.Func(
        [MemberId, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectPayment' : IDL.Func(
        [MemberId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectProfilePhoto' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSearchMembers' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
    'adminSetAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'adminSetMemberActive' : IDL.Func([MemberId, IDL.Bool], [IDL.Bool], []),
    'adminSetPaymentConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetSmsConfig' : IDL.Func(
        [SmsConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminTestSms' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleAdActive' : IDL.Func([AdId], [IDL.Opt(Ad)], []),
    'adminUnverifyProfile' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateAd' : IDL.Func([UpdateAdInput], [IDL.Opt(Ad)], []),
    'adminUpdateAnnouncement' : IDL.Func(
        [AnnouncementId, AnnouncementInput],
        [IDL.Bool],
        [],
      ),
    'adminUpdateCredentials' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateSuccessStory' : IDL.Func(
        [StoryId, SuccessStoryInput],
        [IDL.Bool],
        [],
      ),
    'adminVerifyProfile' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'computeKundaliMilan' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(KundaliResult)],
        ['query'],
      ),
    'computeKundaliScore' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Opt(KundaliResult)],
        ['query'],
      ),
    'computePreciseNakshatra' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Opt(NakshatraData)],
        ['query'],
      ),
    'createProfile' : IDL.Func([MemberInput], [MemberId], []),
    'deleteProfile' : IDL.Func([], [IDL.Bool], []),
    'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAnnouncement' : IDL.Func(
        [AnnouncementId],
        [IDL.Opt(Announcement)],
        ['query'],
      ),
    'getChatGreeting' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getConversation' : IDL.Func(
        [MemberId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getDailyMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemberProfile' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
    'getMyConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getMyMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Member)], ['query']),
    'getNakshatraForDob' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getNakshatraName' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getNearbyMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getProfilePhotoUploadUrl' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getSuccessStory' : IDL.Func([StoryId], [IDL.Opt(SuccessStory)], ['query']),
    'getTodaysMatches' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'listAllMembers' : IDL.Func([], [IDL.Vec(MemberAdminSummary)], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listFeaturedStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'listPendingPayments' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'listPremiumProfiles' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'listProfiles' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Member)], ['query']),
    'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'markAsRead' : IDL.Func(
        [MemberId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordAdClick' : IDL.Func([AdId], [], []),
    'recordAdView' : IDL.Func([AdId], [], []),
    'searchProfiles' : IDL.Func([SearchFilter], [IDL.Vec(Member)], ['query']),
    'sendChatMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'sendMessage' : IDL.Func(
        [MemberId, IDL.Text],
        [IDL.Variant({ 'ok' : MessageId, 'err' : IDL.Text })],
        [],
      ),
    'sendOtp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitPaymentScreenshot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMemberNakshatra' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [MemberId, PaymentStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func([MemberInput], [IDL.Bool], []),
    'updateProfilePhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'upgradeToPremium' : IDL.Func([], [IDL.Bool], []),
    'verifyOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };