export type Gender = "Male" | "Female";
export type MembershipTier = "Free" | "Premium";
export type FamilyType = "Nuclear" | "Joint" | "Extended";
export type EducationLevel =
  | "10th Pass"
  | "12th Pass"
  | "Diploma"
  | "Bachelor's"
  | "Master's"
  | "PhD"
  | "CA"
  | "MBBS"
  | "MD"
  | "LLB";
export type IncomeRange =
  | "Below 2 LPA"
  | "2-5 LPA"
  | "5-10 LPA"
  | "10-15 LPA"
  | "15-25 LPA"
  | "25-50 LPA"
  | "50+ LPA";
export type MaritalStatus = "Never Married" | "Divorced" | "Widowed";
export type Language = "marathi" | "kannada" | "hindi" | "english";
export type PhotoModerationStatus = "Pending" | "Approved" | "Rejected";

export interface Member {
  id: string;
  name: string;
  nameDevanagari?: string;
  age: number;
  gender: Gender;
  dateOfBirth: string;
  birthTime?: string;
  birthPlace?: string;
  height: string;
  city: string;
  state: string;
  nativePlace: string;
  upjati: string; // free text, no enum
  education: EducationLevel;
  occupation: string;
  annualIncome: IncomeRange;
  maritalStatus: MaritalStatus;
  familyType: FamilyType;
  fatherOccupation: string;
  motherOccupation: string;
  siblings: number;
  about: string;
  membershipTier: MembershipTier;
  photoUrl?: string;
  photoAssetId?: string | null;
  photoModerationStatus?: PhotoModerationStatus;
  isVerified?: boolean;
  interests: string[];
  isActive: boolean;
  joinedDate: string;
  partnerAgeMin: number;
  partnerAgeMax: number;
  partnerCity?: string[];
  mobileNumber?: string;
  paymentStatus?: "Pending" | "Uploaded" | "Approved" | "Rejected";
  paymentScreenshotUrl?: string;
  paymentUpiRef?: string;
}

export interface SuccessStory {
  id: string;
  groomName: string;
  brideName: string;
  groomCity: string;
  brideCity: string;
  marriageYear: number;
  story: string;
  photoUrl?: string;
  featured: boolean;
}

export interface Announcement {
  id: string;
  title: string;
  titleDevanagari?: string;
  content: string;
  date: string;
  type: "General" | "Event" | "Promotion";
  active: boolean;
}

export interface SearchFilter {
  ageMin?: number;
  ageMax?: number;
  gender?: Gender;
  upjati?: string;
  city?: string[];
  education?: EducationLevel[];
  occupation?: string;
  incomeMin?: IncomeRange;
  maritalStatus?: MaritalStatus;
}

export interface Ad {
  id: number;
  companyName: string;
  adText: string;
  contactNumber: string;
  websiteLink: string;
  imageUrl: string;
  imageAssetId: string;
  adType: "image" | "text" | "both";
  startDate: bigint;
  endDate: bigint;
  isActive: boolean;
  views: bigint;
  clicks: bigint;
  langText: { mr: string; hi: string; kn: string; en: string };
  createdAt: bigint;
  updatedAt: bigint;
}

export interface AdInput {
  companyName: string;
  adText: string;
  contactNumber: string;
  websiteLink: string;
  imageUrl: string;
  imageAssetId: string;
  adType: "image" | "text" | "both";
  startDate: bigint;
  endDate: bigint;
  langText: { mr: string; hi: string; kn: string; en: string };
}

export interface AdminStats {
  totalMembers: number;
  premiumMembers: number;
  successStories: number;
  activeAnnouncements: number;
  recentJoins: number;
}

export const translations: Record<Language, Record<string, string>> = {
  marathi: {
    // Navigation
    home: "मुखपृष्ठ",
    profiles: "प्रोफाइल्स",
    matches: "जुळवणी",
    plans: "सदस्यता",
    stories: "यशोगाथा",
    adminPanel: "Admin Panel",
    login: "लॉगिन",
    logout: "बाहेर पडा",
    messages: "संदेश",
    search: "शोधा",
    register: "नोंदणी",
    back: "परत",
    joinNow: "₹499 मध्ये सामील व्हा",
    appName: "विवाह सेतू",
    appTagline: "दिगंबर जैन समाजाचे विश्वसनीय वैवाहिक व्यासपीठ",
    community: "दिगंबर जैन समाज",
    langLabel: "MR",

    // Auth/OTP
    mobileLogin: "मोबाईल लॉगिन",
    loginTitle: "विवाह सेतू",
    loginSubtitle: "दिगंबर जैन समाजाचे विश्वसनीय वैवाहिक व्यासपीठ",
    otpTitle: "OTP तपासा",
    otpSendSuccess: "OTP यशस्वीरित्या पाठवला",
    otpSentTo: "OTP पाठवला:",
    otpSendFailed: "OTP पाठवणे अयशस्वी — कृपया पुन्हा प्रयत्न करा",
    rateLimitMsg: "जास्त प्रयत्न. कृपया 1 तास प्रतीक्षा करा.",
    resending: "पुन्हा पाठवत आहे...",
    resendOtp: "OTP पुन्हा पाठवा",
    changeNumber: "नंबर बदला",
    enterMobile: "मोबाईल नंबर प्रविष्ट करा",
    enterOtp: "OTP प्रविष्ट करा",
    sendOtp: "OTP पाठवा",
    verifyOtp: "OTP तपासा",
    invalidMobile: "अवैध मोबाईल नंबर",
    invalidOtp: "अवैध OTP",

    // Registration steps
    step1Title: "वैयक्तिक माहिती",
    step2Title: "समाज माहिती",
    step3Title: "पडताळणी",
    step4Title: "शिक्षण व व्यवसाय",
    step5Title: "कुटुंब माहिती",
    step6Title: "साथीदाराची पसंती",
    step7Title: "फोटो व प्रोफाइल",
    step1: "वैयक्तिक माहिती",
    step2: "शिक्षण व व्यवसाय",
    step3: "कुटुंब माहिती",
    step4: "साथीदाराची पसंती",
    step5: "फोटो अपलोड",
    step6: "प्रोफाइल पूर्वावलोकन",
    step7: "सदस्यता",
    next: "पुढे",
    previous: "मागे",
    submit: "सादर करा",
    stepOf: "पैकी",

    // Profile fields
    firstName: "पहिले नाव",
    lastName: "आडनाव",
    dateOfBirth: "जन्मतारीख",
    gender: "लिंग",
    mobile: "मोबाईल",
    city: "शहर",
    state: "राज्य",
    country: "देश",
    height: "उंची",
    weight: "वजन",
    complexion: "रंग",
    education: "शिक्षण",
    occupation: "व्यवसाय",
    income: "वार्षिक उत्पन्न",
    employerName: "नियोक्ता नाव",
    fatherName: "वडिलांचे नाव",
    motherName: "आईचे नाव",
    siblings: "भावंडे",
    familyType: "कुटुंब प्रकार",
    familyStatus: "कुटुंब स्थिती",
    upjati: "उपजात (ऐच्छिक)",
    partnerMinAge: "साथीदाराचे किमान वय",
    partnerMaxAge: "साथीदाराचे कमाल वय",
    partnerCity: "साथीदाराचे शहर",
    partnerEducation: "साथीदाराचे शिक्षण",
    partnerOccupation: "साथीदाराचा व्यवसाय",
    uploadPhoto: "फोटो अपलोड करा",
    photoInstructions: "JPEG/PNG, कमाल 5MB",
    photoPreview: "फोटो पूर्वावलोकन",
    profilePreview: "प्रोफाइल पूर्वावलोकन",
    submitProfile: "प्रोफाइल सादर करा",
    editProfile: "प्रोफाइल संपादित करा",
    male: "पुरुष",
    female: "महिला",
    employed: "नोकरी",
    selfEmployed: "स्वयंरोजगार",
    business: "व्यवसाय",
    student: "विद्यार्थी",
    other: "इतर",
    nuclear: "विभक्त कुटुंब",
    joint: "संयुक्त कुटुंब",

    // Profile actions
    age: "वय",
    yearsOld: "वर्षे",
    about: "माझ्याबद्दल",
    contactInfo: "संपर्क माहिती",
    profileCompleteness: "प्रोफाइल पूर्णता",
    viewProfile: "प्रोफाइल पहा",
    sendMessage: "संदेश पाठवा",
    expressInterest: "रस दाखवा",
    shortlist: "शॉर्टलिस्ट",
    report: "तक्रार",
    memberSince: "सदस्य झाल्यापासून",
    lastSeen: "शेवटी पाहिले",
    premiumMember: "प्रीमियम सदस्य",
    freeMember: "सदस्य",
    profileStatus: "प्रोफाइल स्थिती",
    pendingApproval: "मंजुरी प्रलंबित",

    // Payment/Plans
    membershipPlans: "सदस्यता योजना",
    freePlan: "प्रीमियम योजना",
    premiumPlan: "प्रीमियम योजना",
    upgradeNow: "आत्ता अपग्रेड करा",
    currentPlan: "सध्याची योजना",
    planPrice: "किंमत",
    planDuration: "कालावधी",
    planBenefits: "फायदे",
    paymentInstructions:
      "UPI QR स्कॅन करा किंवा UPI ID वापरा आणि स्क्रीनशॉट अपलोड करा",
    upiId: "UPI आयडी",
    scanAndPay: "स्कॅन करा आणि ₹499 पेमेंट करा",
    downloadQr: "QR कोड डाउनलोड करा",
    uploadScreenshot: "स्क्रीनशॉट अपलोड करा",
    screenshotUploaded: "स्क्रीनशॉट अपलोड झाला",
    paymentPending: "पेमेंट मंजुरी प्रलंबित आहे",
    paymentApproved: "पेमेंट मंजूर झाले!",
    paymentRejected: "पेमेंट नाकारले गेले",
    paymentNote: "Admin 24 तासांत approve करेल",
    payNow: "आता पेमेंट करा",
    orPayUpi: "किंवा UPI ID वापरा",
    paymentAmount: "पेमेंट रक्कम",
    upiRef: "UPI संदर्भ नंबर",

    // Messaging
    noConversations: "अद्याप कोणतेही संभाषण नाही",
    conversationWith: "यांच्याशी संभाषण",
    loadingMessages: "संदेश लोड होत आहेत...",
    dailyLimitReached: "आजची संदेश मर्यादा संपली!",
    premiumOnly: "फक्त प्रीमियम सदस्यांसाठी",
    messageSent: "संदेश पाठवला",
    messageError: "संदेश पाठवणे अयशस्वी",
    upgradeForUnlimited: "अमर्यादित संदेशांसाठी अपग्रेड करा",
    send: "पाठवा",
    messagesRemaining: "संदेश शिल्लक",
    upgradePrompt: "अमर्यादित संदेशांसाठी प्रीमियम अपग्रेड करा",
    noMessages: "अद्याप संदेश नाहीत",
    typeMessage: "संदेश लिहा...",

    // Success Stories
    successStories: "यशोगाथा",
    ourCouples: "आमची जोडपी",
    addStory: "यशोगाथा जोडा",
    noStories: "अद्याप यशोगाथा नाहीत",
    storyTitle: "शीर्षक",
    storyContent: "यशोगाथा",
    coupleNames: "जोडप्याची नावे",
    marriageDate: "विवाह तारीख",
    shareYourStory: "आपली यशोगाथा सांगा",
    readMore: "अधिक वाचा",
    viewAll: "सर्व पहा",

    // Search/Browse
    searchProfiles: "प्रोफाइल शोधा",
    filterBy: "फिल्टर करा",
    ageRange: "वय श्रेणी",
    minAge: "किमान वय",
    maxAge: "कमाल वय",
    genderFilter: "लिंग",
    cityFilter: "शहर",
    educationFilter: "शिक्षण",
    applyFilters: "फिल्टर लावा",
    clearFilters: "फिल्टर साफ करा",
    noResultsFound: "कोणतेही परिणाम आढळले नाहीत",
    showingResults: "परिणाम दाखवत आहे",
    sortBy: "क्रमवारी",
    newest: "नवीनतम",
    oldest: "जुने",
    relevance: "प्रासंगिकता",
    allProfiles: "सर्व प्रोफाइल",
    featuredProfiles: "वैशिष्ट्यीकृत प्रोफाइल",
    newProfiles: "नवीन प्रोफाइल",
    onlineNow: "ऑनलाईन",

    // Admin
    adminDashboard: "Admin डॅशबोर्ड",
    manageMembers: "सदस्य व्यवस्थापन",
    managePayments: "पेमेंट व्यवस्थापन",
    manageStories: "यशोगाथा व्यवस्थापन",
    moderatePhotos: "फोटो तपासणी",
    manageMessages: "संदेश व्यवस्थापन",
    adminSettings: "Admin सेटिंग्ज",
    totalMembers: "एकूण सदस्य",
    pendingApprovals: "प्रलंबित मंजुरी",
    paidMembers: "पेड सदस्य",
    activeToday: "आज सक्रिय",
    approveProfile: "प्रोफाइल मंजूर करा",
    rejectProfile: "प्रोफाइल नाकारा",
    deleteProfile: "प्रोफाइल हटवा",
    viewDetails: "तपशील पहा",
    approvePayment: "पेमेंट मंजूर करा",
    rejectPayment: "पेमेंट नाकारा",
    paymentDetails: "पेमेंट तपशील",
    transactionId: "व्यवहार क्रमांक",
    approvePhoto: "फोटो मंजूर करा",
    rejectPhoto: "फोटो नाकारा",
    photoModeration: "फोटो मॉडरेशन",
    deleteMessage: "संदेश हटवा",
    messageManagement: "संदेश व्यवस्थापन",
    smsProvider: "SMS प्रदाता",
    smsApiKey: "API की",
    smsSenderName: "प्रेषक नाव",
    enableSms: "SMS सक्रिय करा",
    testSms: "SMS चाचणी",
    saveSmsConfig: "SMS सेटिंग्ज जतन करा",
    smsConfigSaved: "SMS सेटिंग्ज जतन झाल्या",
    adminLogin: "Admin लॉगिन",
    adminPassword: "Admin पासवर्ड",
    adminLogout: "Admin बाहेर पडा",
    exportData: "डेटा एक्सपोर्ट",
    importData: "डेटा इम्पोर्ट",
    refreshData: "डेटा रिफ्रेश",

    // Admin tabs
    dashboard: "डॅशबोर्ड",
    members: "सदस्य",
    payments: "पेमेंट्स",
    adminStories: "यशोगाथा",
    photos: "फोटो",
    adminMessages: "संदेश",
    settings: "सेटिंग्ज",

    // Photo moderation
    approve: "मंजूर करा",
    reject: "नाकारा",
    pending: "प्रलंबित",
    approved: "मंजूर",
    rejected: "नाकारलेले",

    // General UI
    loading: "लोड होत आहे...",
    error: "त्रुटी आली",
    success: "यशस्वी",
    warning: "चेतावणी",
    info: "माहिती",
    noResults: "कोणतेही परिणाम आढळले नाहीत",
    tryAgain: "पुन्हा प्रयत्न करा",
    goBack: "परत जा",
    goHome: "मुखपृष्ठावर जा",
    save: "जतन करा",
    cancel: "रद्द करा",
    delete: "हटवा",
    edit: "संपादित करा",
    confirm: "पुष्टी करा",
    close: "बंद करा",
    yes: "होय",
    no: "नाही",
    ok: "ठीक आहे",
    required: "हे क्षेत्र आवश्यक आहे",
    optional: "ऐच्छिक",
    reset: "रीसेट",
    showMore: "अधिक दाखवा",
    showLess: "कमी दाखवा",
    seeMore: "अधिक पहा",
    fileTooLarge: "फाईल 5MB पेक्षा मोठी नसावी",
    invalidFileType: "फक्त JPEG/PNG चित्रे स्वीकारली जातात",
    uploadFailed: "अपलोड अयशस्वी",
    uploadSuccess: "अपलोड यशस्वी",
    copiedToClipboard: "क्लिपबोर्डवर कॉपी झाले",
    shareLink: "लिंक शेअर करा",
    welcome: "स्वागत आहे",
    welcomeBack: "पुन्हा स्वागत आहे",
    goodbye: "निरोप",
    premiumBadge: "प्रीमियम",
    verifiedBadge: "सत्यापित",
    newBadge: "नवीन",
    marqueeText: "हे ॲप फक्त दिगंबर जैन समाजाच्या वधू व वरासाठी आहे",
    footerCopyright: "© विवाह सेतू. सर्व हक्क राखीव.",
    quickLinks: "त्वरित लिंक",
    browseProfles: "प्रोफाइल ब्राउज करा",
    advancedSearch: "प्रगत शोध",
    todaysMatches: "आजच्या जुळवण्या",
    successStoriesLink: "यशोगाथा",
    joinPremium: "प्रीमियम सामील व्हा",
    alwaysFree: "₹499 मध्ये सामील व्हा",
    // Chatbot
    chatbot_title: "विवाह सेतू सहाय्यक",
    chatbot_placeholder: "संदेश लिहा...",
    chatbot_send: "पाठवा",
    chatbot_greeting: "नमस्कार! मी विवाह सेतू सहाय्यक आहे. मी मदत करण्यास तयार आहे!",
    // Kundali Milan
    kundali_title: "🔮 कुंडली मिलन परिणाम",
    kundali_btn: "कुंडली मिलन",
    kundali_varna: "वर्ण",
    kundali_vashya: "वश्य",
    kundali_tara: "तारा",
    kundali_yoni: "योनी",
    kundali_graha_maitri: "ग्रह मैत्री",
    kundali_gana: "गण",
    kundali_bhakoot: "भकूट",
    kundali_nadi: "नाडी",
    kundali_total: "एकूण गुण",
    kundali_score_of: "36 पैकी",
    kundali_uttam: "उत्तम 💚",
    kundali_madhyam: "मध्यम 🟡",
    kundali_ashubh: "अशुभ 🔴",
    kundali_rashi: "राशी",
    kundali_charan: "चरण",
    kundali_precise_note: "गणना अचूक खगोलीय डेटा वापरते (जन्म वेळेसह)",
    kundali_approx_note: "अंदाजे गणना (जन्म वेळ उपलब्ध नाही)",
    // Birth details
    birth_time: "जन्म वेळ (ऐच्छिक)",
    birth_place: "जन्म स्थळ (ऐच्छिक)",
    nakshatra: "नक्षत्र",
    // Messaging quota
    daily_limit_reached: "आजची संदेश मर्यादा संपली.",
    try_again_at: "पुन्हा {time} नंतर संदेश पाठवा.",
    send_message: "संदेश पाठवा",
    premium_only: "फक्त प्रीमियम सदस्यांसाठी",
    // Payment
    scan_qr_to_pay: "QR स्कॅन करून ₹499 पेमेंट करा",
    payment_pending_approval: "पेमेंट मंजुरी प्रलंबित आहे",
    payment_approved_premium: "पेमेंट मंजूर — तुम्ही आता प्रीमियम सदस्य आहात!",
    // Admin labels
    sms_api_settings: "SMS API सेटिंग्ज",
    test_sms: "SMS चाचणी",
    chatbot_conversations: "चॅटबॉट संभाषणे",
    approve_payment: "पेमेंट मंजूर करा",
    reject_label: "नाकारा",
    // Admin chatbot tab
    chatbot_sessions: "चॅटबॉट संभाषण",
    // Advertisements
    adManagement: "जाहिरात व्यवस्थापन",
    addNewAd: "नवीन जाहिरात जोडा",
    editAd: "जाहिरात संपादित करा",
    deleteAd: "जाहिरात हटवा",
    companyName: "कंपनीचे नाव",
    adText: "जाहिरात मजकूर",
    contactNumber: "संपर्क नंबर",
    websiteLink: "वेबसाइट लिंक",
    adImage: "जाहिरात इमेज URL",
    startDate: "प्रारंभ तारीख",
    endDate: "समाप्ती तारीख",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    expired: "कालबाह्य",
    adType: "जाहिरात प्रकार",
    imageOnly: "फक्त इमेज",
    textOnly: "फक्त मजकूर",
    imageAndText: "इमेज + मजकूर",
    views: "दृश्ये",
    clicks: "क्लिक",
    noAds: "कोणत्याही जाहिराती नाहीत",
    adCreated: "जाहिरात तयार झाली",
    adUpdated: "जाहिरात अपडेट झाली",
    adDeleted: "जाहिरात हटवली",
    adActivated: "जाहिरात सक्रिय केली",
    adDeactivated: "जाहिरात निष्क्रिय केली",
    // New keys
    birthTimeHelper: "जन्म वेळ अचूक कुंडली मिलनसाठी आवश्यक आहे",
    otpServiceUnavailable: "OTP सेवा उपलब्ध नाही, पण लॉगिन चालू आहे",
    passwordChanged: "Admin पासवर्ड यशस्वीरित्या बदलला",
    logoUpdated: "Logo अपडेट झाला — बदल रीलोड नंतर दिसेल",
    perYear: "प्रति वर्ष",
  },

  kannada: {
    // Navigation
    home: "ಮುಖಪುಟ",
    profiles: "ಪ್ರೊಫೈಲ್‌ಗಳು",
    matches: "ಹೊಂದಾಣಿಕೆಗಳು",
    plans: "ಸದಸ್ಯತ್ವ",
    stories: "ಯಶೋಗಾಥೆಗಳು",
    adminPanel: "Admin Panel",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    messages: "ಸಂದೇಶಗಳು",
    search: "ಹುಡುಕಿ",
    register: "ನೋಂದಣಿ",
    back: "ಹಿಂದೆ",
    joinNow: "₹499 ರಲ್ಲಿ ಸೇರಿ",
    appName: "ವಿವಾಹ ಸೇತು",
    appTagline: "ದಿಗಂಬರ ಜೈನ ಸಮಾಜದ ವಿಶ್ವಸನೀಯ ವಿವಾಹ ವೇದಿಕೆ",
    community: "ದಿಗಂಬರ ಜೈನ ಸಮಾಜ",
    langLabel: "KN",

    // Auth/OTP
    mobileLogin: "ಮೊಬೈಲ್ ಲಾಗಿನ್",
    loginTitle: "ವಿವಾಹ ಸೇತು",
    loginSubtitle: "ದಿಗಂಬರ ಜೈನ ಸಮಾಜದ ವಿಶ್ವಸನೀಯ ವಿವಾಹ ವೇದಿಕೆ",
    otpTitle: "OTP ಪರಿಶೀಲಿಸಿ",
    otpSendSuccess: "OTP ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ",
    otpSentTo: "OTP ಕಳುಹಿಸಲಾಗಿದೆ:",
    otpSendFailed: "OTP ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ — ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    rateLimitMsg: "ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳು. ದಯವಿಟ್ಟು 1 ಗಂಟೆ ಕಾಯಿರಿ.",
    resending: "ಮತ್ತೆ ಕಳುಹಿಸುತ್ತಿದ್ದೇವೆ...",
    resendOtp: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    changeNumber: "ನಂಬರ್ ಬದಲಾಯಿಸಿ",
    enterMobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "OTP ಪರಿಶೀಲಿಸಿ",
    invalidMobile: "ಅಮಾನ್ಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    invalidOtp: "ಅಮಾನ್ಯ OTP",

    // Registration steps
    step1Title: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    step2Title: "ಸಮಾಜ ಮಾಹಿತಿ",
    step3Title: "ಪರಿಶೀಲನೆ",
    step4Title: "ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ",
    step5Title: "ಕುಟುಂಬ ಮಾಹಿತಿ",
    step6Title: "ಸಂಗಾತಿ ಆದ್ಯತೆ",
    step7Title: "ಫೋಟೋ ಮತ್ತು ಪ್ರೊಫೈಲ್",
    step1: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    step2: "ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ",
    step3: "ಕುಟುಂಬ ಮಾಹಿತಿ",
    step4: "ಸಂಗಾತಿ ಆದ್ಯತೆ",
    step5: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್",
    step6: "ಪ್ರೊಫೈಲ್ ಪೂರ್ವವೀಕ್ಷಣೆ",
    step7: "ಸದಸ್ಯತ್ವ",
    next: "ಮುಂದೆ",
    previous: "ಹಿಂದೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    stepOf: "ರಲ್ಲಿ",

    // Profile fields
    firstName: "ಮೊದಲ ಹೆಸರು",
    lastName: "ಕೊನೆಯ ಹೆಸರು",
    dateOfBirth: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    gender: "ಲಿಂಗ",
    mobile: "ಮೊಬೈಲ್",
    city: "ನಗರ",
    state: "ರಾಜ್ಯ",
    country: "ದೇಶ",
    height: "ಎತ್ತರ",
    weight: "ತೂಕ",
    complexion: "ಬಣ್ಣ",
    education: "ಶಿಕ್ಷಣ",
    occupation: "ವೃತ್ತಿ",
    income: "ವಾರ್ಷಿಕ ಆದಾಯ",
    employerName: "ಉದ್ಯೋಗದಾತ ಹೆಸರು",
    fatherName: "ತಂದೆಯ ಹೆಸರು",
    motherName: "ತಾಯಿಯ ಹೆಸರು",
    siblings: "ಒಡಹುಟ್ಟಿದವರು",
    familyType: "ಕುಟುಂಬ ಪ್ರಕಾರ",
    familyStatus: "ಕುಟುಂಬ ಸ್ಥಿತಿ",
    upjati: "ಉಪಜಾತಿ (ಐಚ್ಛಿಕ)",
    partnerMinAge: "ಸಂಗಾತಿಯ ಕನಿಷ್ಠ ವಯಸ್ಸು",
    partnerMaxAge: "ಸಂಗಾತಿಯ ಗರಿಷ್ಠ ವಯಸ್ಸು",
    partnerCity: "ಸಂಗಾತಿಯ ನಗರ",
    partnerEducation: "ಸಂಗಾತಿಯ ಶಿಕ್ಷಣ",
    partnerOccupation: "ಸಂಗಾತಿಯ ವೃತ್ತಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    photoInstructions: "JPEG/PNG, ಗರಿಷ್ಠ 5MB",
    photoPreview: "ಫೋಟೋ ಪೂರ್ವವೀಕ್ಷಣೆ",
    profilePreview: "ಪ್ರೊಫೈಲ್ ಪೂರ್ವವೀಕ್ಷಣೆ",
    submitProfile: "ಪ್ರೊಫೈಲ್ ಸಲ್ಲಿಸಿ",
    editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    employed: "ಉದ್ಯೋಗ",
    selfEmployed: "ಸ್ವ-ಉದ್ಯೋಗ",
    business: "ವ್ಯವಹಾರ",
    student: "ವಿದ್ಯಾರ್ಥಿ",
    other: "ಇತರೆ",
    nuclear: "ವಿಭಕ್ತ ಕುಟುಂಬ",
    joint: "ಅವಿಭಕ್ತ ಕುಟುಂಬ",

    // Profile actions
    age: "ವಯಸ್ಸು",
    yearsOld: "ವರ್ಷ",
    about: "ನನ್ನ ಬಗ್ಗೆ",
    contactInfo: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    profileCompleteness: "ಪ್ರೊಫೈಲ್ ಸಂಪೂರ್ಣತೆ",
    viewProfile: "ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    expressInterest: "ಆಸಕ್ತಿ ತೋರಿಸಿ",
    shortlist: "ಶಾರ್ಟ್‌ಲಿಸ್ಟ್",
    report: "ದೂರು",
    memberSince: "ಸದಸ್ಯತ್ವ ದಿನಾಂಕ",
    lastSeen: "ಕೊನೆಯ ಭೇಟಿ",
    premiumMember: "ಪ್ರೀಮಿಯಂ ಸದಸ್ಯ",
    freeMember: "ಸದಸ್ಯ",
    profileStatus: "ಪ್ರೊಫೈಲ್ ಸ್ಥಿತಿ",
    pendingApproval: "ಅನುಮೋದನೆ ಬಾಕಿ",

    // Payment/Plans
    membershipPlans: "ಸದಸ್ಯತ್ವ ಯೋಜನೆಗಳು",
    freePlan: "ಪ್ರೀಮಿಯಂ ಯೋಜನೆ",
    premiumPlan: "ಪ್ರೀಮಿಯಂ ಯೋಜನೆ",
    upgradeNow: "ಈಗ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    currentPlan: "ಪ್ರಸ್ತುತ ಯೋಜನೆ",
    planPrice: "ಬೆಲೆ",
    planDuration: "ಅವಧಿ",
    planBenefits: "ಪ್ರಯೋಜನಗಳು",
    paymentInstructions:
      "UPI QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಥವಾ UPI ID ಬಳಸಿ ಮತ್ತು ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    upiId: "UPI ಐಡಿ",
    scanAndPay: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ₹499 ಪಾವತಿಸಿ",
    downloadQr: "QR ಕೋಡ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadScreenshot: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    screenshotUploaded: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ",
    paymentPending: "ಪಾವತಿ ಅನುಮೋದನೆ ಬಾಕಿ ಇದೆ",
    paymentApproved: "ಪಾವತಿ ಅನುಮೋದಿಸಲಾಗಿದೆ!",
    paymentRejected: "ಪಾವತಿ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    paymentNote: "Admin 24 ಗಂಟೆಯಲ್ಲಿ approve ಮಾಡುತ್ತಾರೆ",
    payNow: "ಈಗ ಪಾವತಿ ಮಾಡಿ",
    orPayUpi: "ಅಥವಾ UPI ID ಬಳಸಿ",
    paymentAmount: "ಪಾವತಿ ಮೊತ್ತ",
    upiRef: "UPI ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ",

    // Messaging
    noConversations: "ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ",
    conversationWith: "ಜೊತೆ ಸಂಭಾಷಣೆ",
    loadingMessages: "ಸಂದೇಶಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    dailyLimitReached: "ಇಂದಿನ ಸಂದೇಶ ಮಿತಿ ತಲುಪಿದೆ!",
    premiumOnly: "ಪ್ರೀಮಿಯಂ ಸದಸ್ಯರಿಗೆ ಮಾತ್ರ",
    messageSent: "ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ",
    messageError: "ಸಂದೇಶ ಕಳುಹಿಸಲು ವಿಫಲ",
    upgradeForUnlimited: "ಅಪರಿಮಿತ ಸಂದೇಶಗಳಿಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    send: "ಕಳುಹಿಸಿ",
    messagesRemaining: "ಸಂದೇಶಗಳು ಉಳಿದಿವೆ",
    upgradePrompt: "ಅನಿಯಮಿತ ಸಂದೇಶಗಳಿಗೆ ಪ್ರೀಮಿಯಂ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    noMessages: "ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ",
    typeMessage: "ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...",

    // Success Stories
    successStories: "ಯಶೋಗಾಥೆಗಳು",
    ourCouples: "ನಮ್ಮ ದಂಪತಿಗಳು",
    addStory: "ಯಶೋಗಾಥೆ ಸೇರಿಸಿ",
    noStories: "ಇನ್ನೂ ಯಶೋಗಾಥೆಗಳಿಲ್ಲ",
    storyTitle: "ಶೀರ್ಷಿಕೆ",
    storyContent: "ಯಶೋಗಾಥೆ",
    coupleNames: "ದಂಪತಿ ಹೆಸರು",
    marriageDate: "ವಿವಾಹ ದಿನಾಂಕ",
    shareYourStory: "ನಿಮ್ಮ ಯಶೋಗಾಥೆ ಹಂಚಿಕೊಳ್ಳಿ",
    readMore: "ಇನ್ನಷ್ಟು ಓದಿ",
    viewAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",

    // Search/Browse
    searchProfiles: "ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಹುಡುಕಿ",
    filterBy: "ಫಿಲ್ಟರ್",
    ageRange: "ವಯಸ್ಸಿನ ಶ್ರೇಣಿ",
    minAge: "ಕನಿಷ್ಠ ವಯಸ್ಸು",
    maxAge: "ಗರಿಷ್ಠ ವಯಸ್ಸು",
    genderFilter: "ಲಿಂಗ",
    cityFilter: "ನಗರ",
    educationFilter: "ಶಿಕ್ಷಣ",
    applyFilters: "ಫಿಲ್ಟರ್ ಅನ್ವಯಿಸಿ",
    clearFilters: "ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ",
    noResultsFound: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
    showingResults: "ಫಲಿತಾಂಶಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ",
    sortBy: "ವಿಂಗಡಿಸಿ",
    newest: "ಹೊಸ",
    oldest: "ಹಳೆಯ",
    relevance: "ಪ್ರಸ್ತುತತೆ",
    allProfiles: "ಎಲ್ಲ ಪ್ರೊಫೈಲ್‌ಗಳು",
    featuredProfiles: "ವೈಶಿಷ್ಟ್ಯ ಪ್ರೊಫೈಲ್‌ಗಳು",
    newProfiles: "ಹೊಸ ಪ್ರೊಫೈಲ್‌ಗಳು",
    onlineNow: "ಆನ್‌ಲೈನ್",

    // Admin
    adminDashboard: "Admin ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    manageMembers: "ಸದಸ್ಯ ನಿರ್ವಹಣೆ",
    managePayments: "ಪಾವತಿ ನಿರ್ವಹಣೆ",
    manageStories: "ಯಶೋಗಾಥೆ ನಿರ್ವಹಣೆ",
    moderatePhotos: "ಫೋಟೋ ಮಧ್ಯಸ್ಥಿಕೆ",
    manageMessages: "ಸಂದೇಶ ನಿರ್ವಹಣೆ",
    adminSettings: "Admin ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    totalMembers: "ಒಟ್ಟು ಸದಸ್ಯರು",
    pendingApprovals: "ಬಾಕಿ ಅನುಮೋದನೆ",
    paidMembers: "ಪ್ರೀಮಿಯಂ ಸದಸ್ಯರು",
    activeToday: "ಇಂದು ಸಕ್ರಿಯ",
    approveProfile: "ಪ್ರೊಫೈಲ್ ಅನುಮೋದಿಸಿ",
    rejectProfile: "ಪ್ರೊಫೈಲ್ ತಿರಸ್ಕರಿಸಿ",
    deleteProfile: "ಪ್ರೊಫೈಲ್ ಅಳಿಸಿ",
    viewDetails: "ವಿವರ ನೋಡಿ",
    approvePayment: "ಪಾವತಿ ಅನುಮೋದಿಸಿ",
    rejectPayment: "ಪಾವತಿ ತಿರಸ್ಕರಿಸಿ",
    paymentDetails: "ಪಾವತಿ ವಿವರ",
    transactionId: "ವ್ಯವಹಾರ ಐಡಿ",
    approvePhoto: "ಫೋಟೋ ಅನುಮೋದಿಸಿ",
    rejectPhoto: "ಫೋಟೋ ತಿರಸ್ಕರಿಸಿ",
    photoModeration: "ಫೋಟೋ ಮಾಡರೇಶನ್",
    deleteMessage: "ಸಂದೇಶ ಅಳಿಸಿ",
    messageManagement: "ಸಂದೇಶ ನಿರ್ವಹಣೆ",
    smsProvider: "SMS ಪ್ರದಾತ",
    smsApiKey: "API ಕೀ",
    smsSenderName: "ಕಳುಹಿಸುವವರ ಹೆಸರು",
    enableSms: "SMS ಸಕ್ರಿಯಗೊಳಿಸಿ",
    testSms: "SMS ಪರೀಕ್ಷಿಸಿ",
    saveSmsConfig: "SMS ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
    smsConfigSaved: "SMS ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಉಳಿಸಲಾಗಿದೆ",
    adminLogin: "Admin ಲಾಗಿನ್",
    adminPassword: "Admin ಪಾಸ್‌ವರ್ಡ್",
    adminLogout: "Admin ಲಾಗ್ ಔಟ್",
    exportData: "ಡೇಟಾ ಎಕ್ಸ್‌ಪೋರ್ಟ್",
    importData: "ಡೇಟಾ ಇಂಪೋರ್ಟ್",
    refreshData: "ಡೇಟಾ ರಿಫ್ರೆಶ್",

    // Admin tabs
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    members: "ಸದಸ್ಯರು",
    payments: "ಪಾವತಿಗಳು",
    adminStories: "ಯಶೋಗಾಥೆ",
    photos: "ಫೋಟೋಗಳು",
    adminMessages: "ಸಂದೇಶಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",

    // Photo moderation
    approve: "ಅನುಮೋದಿಸಿ",
    reject: "ತಿರಸ್ಕರಿಸಿ",
    pending: "ಬಾಕಿ",
    approved: "ಅನುಮೋದಿತ",
    rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",

    // General UI
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ದೋಷ ಸಂಭವಿಸಿದೆ",
    success: "ಯಶಸ್ವಿ",
    warning: "ಎಚ್ಚರಿಕೆ",
    info: "ಮಾಹಿತಿ",
    noResults: "ಯಾವುದೇ ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
    tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    goBack: "ಹಿಂದೆ ಹೋಗಿ",
    goHome: "ಮನೆಗೆ ಹೋಗಿ",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದು",
    delete: "ಅಳಿಸಿ",
    edit: "ಸಂಪಾದಿಸಿ",
    confirm: "ದೃಢೀಕರಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    ok: "ಸರಿ",
    required: "ಈ ಕ್ಷೇತ್ರ ಅಗತ್ಯವಿದೆ",
    optional: "ಐಚ್ಛಿಕ",
    reset: "ರೀಸೆಟ್",
    showMore: "ಇನ್ನಷ್ಟು ತೋರಿಸಿ",
    showLess: "ಕಡಿಮೆ ತೋರಿಸಿ",
    seeMore: "ಇನ್ನಷ್ಟು ನೋಡಿ",
    fileTooLarge: "ಫೈಲ್ 5MB ಮೀರಬಾರದು",
    invalidFileType: "ಕೇವಲ JPEG/PNG ಚಿತ್ರಗಳನ್ನು ಸ್ವೀಕರಿಸಲಾಗುತ್ತದೆ",
    uploadFailed: "ಅಪ್‌ಲೋಡ್ ವಿಫಲ",
    uploadSuccess: "ಅಪ್‌ಲೋಡ್ ಯಶಸ್ವಿ",
    copiedToClipboard: "ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ",
    shareLink: "ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ",
    welcome: "ಸ್ವಾಗತ",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    goodbye: "ವಿದಾಯ",
    premiumBadge: "ಪ್ರೀಮಿಯಂ",
    verifiedBadge: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    newBadge: "ಹೊಸ",
    marqueeText: "ಈ ಅಪ್ಲಿಕೇಶನ್ ಕೇವಲ ದಿಗಂಬರ ಜೈನ ಸಮಾಜದ ವಧು ಮತ್ತು ವರರಿಗಾಗಿ ಮಾತ್ರ",
    footerCopyright: "© ವಿವಾಹ ಸೇತು. ಎಲ್ಲ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    quickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    browseProfles: "ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    advancedSearch: "ಸುಧಾರಿತ ಹುಡುಕಾಟ",
    todaysMatches: "ಇಂದಿನ ಹೊಂದಾಣಿಕೆಗಳು",
    successStoriesLink: "ಯಶೋಗಾಥೆಗಳು",
    joinPremium: "ಪ್ರೀಮಿಯಂ ಸೇರಿ",
    alwaysFree: "₹499 ರಲ್ಲಿ ಸೇರಿ",
    // Chatbot
    chatbot_title: "ವಿವಾಹ ಸೇತು ಸಹಾಯಕ",
    chatbot_placeholder: "ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...",
    chatbot_send: "ಕಳುಹಿಸಿ",
    chatbot_greeting: "ನಮಸ್ಕಾರ! ನಾನು ವಿವಾಹ ಸೇತು ಸಹಾಯಕ. ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧ!",
    // Kundali Milan
    kundali_title: "🔮 ಕುಂಡಲಿ ಮಿಲನ ಫಲಿತಾಂಶ",
    kundali_btn: "ಕುಂಡಲಿ ಮಿಲನ",
    kundali_varna: "ವರ್ಣ",
    kundali_vashya: "ವಶ್ಯ",
    kundali_tara: "ತಾರಾ",
    kundali_yoni: "ಯೋನಿ",
    kundali_graha_maitri: "ಗ್ರಹ ಮೈತ್ರಿ",
    kundali_gana: "ಗಣ",
    kundali_bhakoot: "ಭಕೂಟ",
    kundali_nadi: "ನಾಡಿ",
    kundali_total: "ಒಟ್ಟು ಗುಣ",
    kundali_score_of: "36 ರಲ್ಲಿ",
    kundali_uttam: "ಉತ್ತಮ 💚",
    kundali_madhyam: "ಮಧ್ಯಮ 🟡",
    kundali_ashubh: "ಅಶುಭ 🔴",
    kundali_rashi: "ರಾಶಿ",
    kundali_charan: "ಚರಣ",
    kundali_precise_note: "ಗಣನೆ ನಿಖರ ಖಗೋಳ ಡೇಟಾ ಬಳಸುತ್ತದೆ (ಜನ್ಮ ಸಮಯ ಸಹಿತ)",
    kundali_approx_note: "ಅಂದಾಜು ಗಣನೆ (ಜನ್ಮ ಸಮಯ ಲಭ್ಯವಿಲ್ಲ)",
    // Birth details
    birth_time: "ಹುಟ್ಟಿದ ಸಮಯ (ಐಚ್ಛಿಕ)",
    birth_place: "ಹುಟ್ಟಿದ ಸ್ಥಳ (ಐಚ್ಛಿಕ)",
    nakshatra: "ನಕ್ಷತ್ರ",
    // Messaging quota
    daily_limit_reached: "ಇಂದಿನ ಸಂದೇಶ ಮಿತಿ ತಲುಪಿದೆ.",
    try_again_at: "{time} ನಂತರ ಮತ್ತೆ ಕಳುಹಿಸಿ.",
    send_message: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    premium_only: "ಪ್ರೀಮಿಯಂ ಸದಸ್ಯರಿಗೆ ಮಾತ್ರ",
    // Payment
    scan_qr_to_pay: "QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ₹499 ಪಾವತಿಸಿ",
    payment_pending_approval: "ಪಾವತಿ ಅನುಮೋದನೆ ಬಾಕಿ ಇದೆ",
    payment_approved_premium: "ಪಾವತಿ ಅನುಮೋದಿಸಲಾಗಿದೆ — ನೀವು ಪ್ರೀಮಿಯಂ ಸದಸ್ಯರು!",
    // Admin labels
    sms_api_settings: "SMS API ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    test_sms: "SMS ಪರೀಕ್ಷಿಸಿ",
    chatbot_conversations: "ಚಾಟ್‌ಬಾಟ್ ಸಂಭಾಷಣೆಗಳು",
    approve_payment: "ಪಾವತಿ ಅನುಮೋದಿಸಿ",
    reject_label: "ತಿರಸ್ಕರಿಸಿ",
    chatbot_sessions: "ಚಾಟ್‌ಬಾಟ್ ಸಂಭಾಷಣೆಗಳು",
    // Advertisements
    adManagement: "ಜಾಹೀರಾತು ನಿರ್ವಹಣೆ",
    addNewAd: "ಹೊಸ ಜಾಹೀರಾತು ಸೇರಿಸಿ",
    editAd: "ಜಾಹೀರಾತು ಸಂಪಾದಿಸಿ",
    deleteAd: "ಜಾಹೀರಾತು ಅಳಿಸಿ",
    companyName: "ಕಂಪನಿ ಹೆಸರು",
    adText: "ಜಾಹೀರಾತು ಪಠ್ಯ",
    contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    websiteLink: "ವೆಬ್‌ಸೈಟ್ ಲಿಂಕ್",
    adImage: "ಜಾಹೀರಾತು ಚಿತ್ರ URL",
    startDate: "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
    endDate: "ಅಂತ್ಯ ದಿನಾಂಕ",
    active: "ಸಕ್ರಿಯ",
    inactive: "ನಿಷ್ಕ್ರಿಯ",
    expired: "ಮುಕ್ತಾಯ",
    adType: "ಜಾಹೀರಾತು ಪ್ರಕಾರ",
    imageOnly: "ಕೇವಲ ಚಿತ್ರ",
    textOnly: "ಕೇವಲ ಪಠ್ಯ",
    imageAndText: "ಚಿತ್ರ + ಪಠ್ಯ",
    views: "ವೀಕ್ಷಣೆಗಳು",
    clicks: "ಕ್ಲಿಕ್‌ಗಳು",
    noAds: "ಯಾವುದೇ ಜಾಹೀರಾತುಗಳಿಲ್ಲ",
    adCreated: "ಜಾಹೀರಾತು ರಚಿಸಲಾಗಿದೆ",
    adUpdated: "ಜಾಹೀರಾತು ನವೀಕರಿಸಲಾಗಿದೆ",
    adDeleted: "ಜಾಹೀರಾತು ಅಳಿಸಲಾಗಿದೆ",
    adActivated: "ಜಾಹೀರಾತು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    adDeactivated: "ಜಾಹೀರಾತು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    // New keys
    birthTimeHelper: "ನಿಖರ ಕುಂಡಲಿ ಮಿಲನಕ್ಕಾಗಿ ಜನ್ಮ ಸಮಯ ಅಗತ್ಯ",
    otpServiceUnavailable: "OTP ಸೇವೆ ಲಭ್ಯವಿಲ್ಲ, ಆದರೆ ಲಾಗಿನ್ ಮುಂದುವರೆಯುತ್ತದೆ",
    passwordChanged: "Admin ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ",
    logoUpdated: "Logo ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ — ರಿಲೋಡ್ ನಂತರ ಬದಲಾವಣೆ ಕಾಣಿಸುತ್ತದೆ",
    perYear: "ಪ್ರತಿ ವರ್ಷ",
  },

  hindi: {
    // Navigation
    home: "मुखपृष्ठ",
    profiles: "प्रोफाइल",
    matches: "मेल",
    plans: "सदस्यता",
    stories: "सफलता की कहानियाँ",
    adminPanel: "Admin Panel",
    login: "लॉगिन",
    logout: "बाहर निकलें",
    messages: "संदेश",
    search: "खोजें",
    register: "पंजीकरण",
    back: "वापस",
    joinNow: "₹499 में जुड़ें",
    appName: "विवाह सेतु",
    appTagline: "दिगंबर जैन समाज का विश्वसनीय वैवाहिक मंच",
    community: "दिगंबर जैन समाज",
    langLabel: "HI",

    // Auth/OTP
    mobileLogin: "मोबाईल लॉगिन",
    loginTitle: "विवाह सेतु",
    loginSubtitle: "दिगंबर जैन समाज का विश्वसनीय वैवाहिक मंच",
    otpTitle: "OTP सत्यापित करें",
    otpSendSuccess: "OTP सफलतापूर्वक भेजा गया",
    otpSentTo: "OTP भेजा गया:",
    otpSendFailed: "OTP भेजना असफल रहा — कृपया पुनः प्रयास करें",
    rateLimitMsg: "बहुत अधिक प्रयास। कृपया 1 घंटा प्रतीक्षा करें।",
    resending: "पुनः भेज रहे हैं...",
    resendOtp: "OTP पुनः भेजें",
    changeNumber: "नंबर बदलें",
    enterMobile: "मोबाइल नंबर दर्ज करें",
    enterOtp: "OTP दर्ज करें",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    invalidMobile: "अमान्य मोबाइल नंबर",
    invalidOtp: "अमान्य OTP",

    // Registration steps
    step1Title: "व्यक्तिगत जानकारी",
    step2Title: "समाज जानकारी",
    step3Title: "सत्यापन",
    step4Title: "शिक्षा एवं व्यवसाय",
    step5Title: "परिवार की जानकारी",
    step6Title: "साथी की पसंद",
    step7Title: "फ़ोटो और प्रोफाइल",
    step1: "व्यक्तिगत जानकारी",
    step2: "शिक्षा एवं व्यवसाय",
    step3: "परिवार की जानकारी",
    step4: "साथी की पसंद",
    step5: "फ़ोटो अपलोड",
    step6: "प्रोफाइल पूर्वावलोकन",
    step7: "सदस्यता",
    next: "आगे",
    previous: "पीछे",
    submit: "जमा करें",
    stepOf: "में से",

    // Profile fields
    firstName: "पहला नाम",
    lastName: "उपनाम",
    dateOfBirth: "जन्मतिथि",
    gender: "लिंग",
    mobile: "मोबाइल",
    city: "शहर",
    state: "राज्य",
    country: "देश",
    height: "ऊंचाई",
    weight: "वज़न",
    complexion: "रंग",
    education: "शिक्षा",
    occupation: "व्यवसाय",
    income: "वार्षिक आय",
    employerName: "नियोक्ता नाम",
    fatherName: "पिता का नाम",
    motherName: "माता का नाम",
    siblings: "भाई-बहन",
    familyType: "परिवार प्रकार",
    familyStatus: "परिवार स्थिति",
    upjati: "उपजाति (वैकल्पिक)",
    partnerMinAge: "साथी की न्यूनतम आयु",
    partnerMaxAge: "साथी की अधिकतम आयु",
    partnerCity: "साथी का शहर",
    partnerEducation: "साथी की शिक्षा",
    partnerOccupation: "साथी का व्यवसाय",
    uploadPhoto: "फ़ोटो अपलोड करें",
    photoInstructions: "JPEG/PNG, अधिकतम 5MB",
    photoPreview: "फ़ोटो पूर्वावलोकन",
    profilePreview: "प्रोफाइल पूर्वावलोकन",
    submitProfile: "प्रोफाइल जमा करें",
    editProfile: "प्रोफाइल संपादित करें",
    male: "पुरुष",
    female: "महिला",
    employed: "नौकरी",
    selfEmployed: "स्वरोजगार",
    business: "व्यवसाय",
    student: "छात्र",
    other: "अन्य",
    nuclear: "एकल परिवार",
    joint: "संयुक्त परिवार",

    // Profile actions
    age: "आयु",
    yearsOld: "वर्ष",
    about: "मेरे बारे में",
    contactInfo: "संपर्क जानकारी",
    profileCompleteness: "प्रोफाइल पूर्णता",
    viewProfile: "प्रोफाइल देखें",
    sendMessage: "संदेश भेजें",
    expressInterest: "रुचि दिखाएं",
    shortlist: "शॉर्टलिस्ट",
    report: "शिकायत",
    memberSince: "सदस्य बने",
    lastSeen: "अंतिम बार देखा",
    premiumMember: "प्रीमियम सदस्य",
    freeMember: "सदस्य",
    profileStatus: "प्रोफाइल स्थिति",
    pendingApproval: "स्वीकृति लंबित",

    // Payment/Plans
    membershipPlans: "सदस्यता योजना",
    freePlan: "प्रीमियम योजना",
    premiumPlan: "प्रीमियम योजना",
    upgradeNow: "अभी अपग्रेड करें",
    currentPlan: "वर्तमान योजना",
    planPrice: "कीमत",
    planDuration: "अवधि",
    planBenefits: "लाभ",
    paymentInstructions:
      "UPI QR स्कैन करें या UPI ID का उपयोग करें और स्क्रीनशॉट अपलोड करें",
    upiId: "UPI आईडी",
    scanAndPay: "स्कैन करें और ₹499 भुगतान करें",
    downloadQr: "QR कोड डाउनलोड करें",
    uploadScreenshot: "स्क्रीनशॉट अपलोड करें",
    screenshotUploaded: "स्क्रीनशॉट अपलोड हुआ",
    paymentPending: "भुगतान स्वीकृति प्रतीक्षारत है",
    paymentApproved: "भुगतान स्वीकृत हो गया!",
    paymentRejected: "भुगतान अस्वीकृत किया गया",
    paymentNote: "Admin 24 घंटे में approve करेगा",
    payNow: "अभी भुगतान करें",
    orPayUpi: "या UPI ID उपयोग करें",
    paymentAmount: "भुगतान राशि",
    upiRef: "UPI संदर्भ संख्या",

    // Messaging
    noConversations: "अभी कोई बातचीत नहीं",
    conversationWith: "के साथ बातचीत",
    loadingMessages: "संदेश लोड हो रहे हैं...",
    dailyLimitReached: "आज की संदेश सीमा समाप्त!",
    premiumOnly: "केवल प्रीमियम सदस्यों के लिए",
    messageSent: "संदेश भेजा गया",
    messageError: "संदेश भेजना असफल",
    upgradeForUnlimited: "असीमित संदेशों के लिए अपग्रेड करें",
    send: "भेजें",
    messagesRemaining: "संदेश शेष",
    upgradePrompt: "असीमित संदेशों के लिए प्रीमियम अपग्रेड करें",
    noMessages: "अभी तक कोई संदेश नहीं",
    typeMessage: "संदेश लिखें...",

    // Success Stories
    successStories: "सफलता की कहानियाँ",
    ourCouples: "हमारे जोड़े",
    addStory: "कहानी जोड़ें",
    noStories: "अभी कोई कहानियाँ नहीं",
    storyTitle: "शीर्षक",
    storyContent: "सफलता की कहानी",
    coupleNames: "जोड़े के नाम",
    marriageDate: "विवाह दिनांक",
    shareYourStory: "अपनी कहानी साझा करें",
    readMore: "और पढ़ें",
    viewAll: "सभी देखें",

    // Search/Browse
    searchProfiles: "प्रोफाइल खोजें",
    filterBy: "फ़िल्टर",
    ageRange: "आयु सीमा",
    minAge: "न्यूनतम आयु",
    maxAge: "अधिकतम आयु",
    genderFilter: "लिंग",
    cityFilter: "शहर",
    educationFilter: "शिक्षा",
    applyFilters: "फ़िल्टर लागू करें",
    clearFilters: "फ़िल्टर साफ करें",
    noResultsFound: "कोई परिणाम नहीं मिला",
    showingResults: "परिणाम दिखा रहे हैं",
    sortBy: "क्रमबद्ध करें",
    newest: "नवीनतम",
    oldest: "सबसे पुराना",
    relevance: "प्रासंगिकता",
    allProfiles: "सभी प्रोफाइल",
    featuredProfiles: "विशेष प्रोफाइल",
    newProfiles: "नई प्रोफाइल",
    onlineNow: "ऑनलाइन",

    // Admin
    adminDashboard: "Admin डैशबोर्ड",
    manageMembers: "सदस्य प्रबंधन",
    managePayments: "भुगतान प्रबंधन",
    manageStories: "कहानी प्रबंधन",
    moderatePhotos: "फ़ोटो मॉडरेशन",
    manageMessages: "संदेश प्रबंधन",
    adminSettings: "Admin सेटिंग्स",
    totalMembers: "कुल सदस्य",
    pendingApprovals: "लंबित स्वीकृतियाँ",
    paidMembers: "प्रीमियम सदस्य",
    activeToday: "आज सक्रिय",
    approveProfile: "प्रोफाइल स्वीकृत करें",
    rejectProfile: "प्रोफाइल अस्वीकार करें",
    deleteProfile: "प्रोफाइल हटाएं",
    viewDetails: "विवरण देखें",
    approvePayment: "भुगतान स्वीकृत करें",
    rejectPayment: "भुगतान अस्वीकार करें",
    paymentDetails: "भुगतान विवरण",
    transactionId: "लेनदेन आईडी",
    approvePhoto: "फ़ोटो स्वीकृत करें",
    rejectPhoto: "फ़ोटो अस्वीकार करें",
    photoModeration: "फ़ोटो मॉडरेशन",
    deleteMessage: "संदेश हटाएं",
    messageManagement: "संदेश प्रबंधन",
    smsProvider: "SMS प्रदाता",
    smsApiKey: "API कुंजी",
    smsSenderName: "प्रेषक नाम",
    enableSms: "SMS सक्रिय करें",
    testSms: "SMS परीक्षण",
    saveSmsConfig: "SMS सेटिंग्स सहेजें",
    smsConfigSaved: "SMS सेटिंग्स सहेजी गईं",
    adminLogin: "Admin लॉगिन",
    adminPassword: "Admin पासवर्ड",
    adminLogout: "Admin बाहर निकलें",
    exportData: "डेटा एक्सपोर्ट",
    importData: "डेटा इम्पोर्ट",
    refreshData: "डेटा रिफ्रेश",

    // Admin tabs
    dashboard: "डैशबोर्ड",
    members: "सदस्य",
    payments: "भुगतान",
    adminStories: "सफलता की कहानियां",
    photos: "फ़ोटो",
    adminMessages: "संदेश",
    settings: "सेटिंग्स",

    // Photo moderation
    approve: "स्वीकृत करें",
    reject: "अस्वीकृत करें",
    pending: "प्रतीक्षारत",
    approved: "स्वीकृत",
    rejected: "अस्वीकृत",

    // General UI
    loading: "लोड हो रहा है...",
    error: "त्रुटि हुई",
    success: "सफल",
    warning: "चेतावनी",
    info: "जानकारी",
    noResults: "कोई परिणाम नहीं मिला",
    tryAgain: "पुनः प्रयास करें",
    goBack: "वापस जाएं",
    goHome: "होम जाएं",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    confirm: "पुष्टि करें",
    close: "बंद करें",
    yes: "हाँ",
    no: "नहीं",
    ok: "ठीक है",
    required: "यह फ़ील्ड आवश्यक है",
    optional: "वैकल्पिक",
    reset: "रीसेट",
    showMore: "और दिखाएं",
    showLess: "कम दिखाएं",
    seeMore: "और देखें",
    fileTooLarge: "फ़ाइल 5MB से बड़ी नहीं होनी चाहिए",
    invalidFileType: "केवल JPEG/PNG छवियां स्वीकार की जाती हैं",
    uploadFailed: "अपलोड असफल",
    uploadSuccess: "अपलोड सफल",
    copiedToClipboard: "क्लिपबोर्ड पर कॉपी हुआ",
    shareLink: "लिंक साझा करें",
    welcome: "स्वागत है",
    welcomeBack: "वापसी पर स्वागत है",
    goodbye: "अलविदा",
    premiumBadge: "प्रीमियम",
    verifiedBadge: "सत्यापित",
    newBadge: "नया",
    marqueeText: "यह ऐप केवल दिगंबर जैन समाज के वधू और वर के लिए है",
    footerCopyright: "© विवाह सेतु. सर्वाधिकार सुरक्षित.",
    quickLinks: "त्वरित लिंक",
    browseProfles: "प्रोफाइल ब्राउज़ करें",
    advancedSearch: "उन्नत खोज",
    todaysMatches: "आज के मेल",
    successStoriesLink: "सफलता की कहानियां",
    joinPremium: "प्रीमियम में जुड़ें",
    alwaysFree: "₹499 में जुड़ें",
    // Chatbot
    chatbot_title: "विवाह सेतु सहायक",
    chatbot_placeholder: "संदेश लिखें...",
    chatbot_send: "भेजें",
    chatbot_greeting: "नमस्ते! मैं विवाह सेतु सहायक हूं। मदद के लिए तैयार हूं!",
    // Kundali Milan
    kundali_title: "🔮 कुंडली मिलन परिणाम",
    kundali_btn: "कुंडली मिलन",
    kundali_varna: "वर्ण",
    kundali_vashya: "वश्य",
    kundali_tara: "तारा",
    kundali_yoni: "योनी",
    kundali_graha_maitri: "ग्रह मैत्री",
    kundali_gana: "गण",
    kundali_bhakoot: "भकूट",
    kundali_nadi: "नाड़ी",
    kundali_total: "कुल गुण",
    kundali_score_of: "36 में से",
    kundali_uttam: "उत्तम 💚",
    kundali_madhyam: "मध्यम 🟡",
    kundali_ashubh: "अशुभ 🔴",
    kundali_rashi: "राशि",
    kundali_charan: "चरण",
    kundali_precise_note: "गणना सटीक खगोलीय डेटा का उपयोग करती है (जन्म समय सहित)",
    kundali_approx_note: "अनुमानित गणना (जन्म समय उपलब्ध नहीं)",
    // Birth details
    birth_time: "जन्म समय (वैकल्पिक)",
    birth_place: "जन्म स्थान (वैकल्पिक)",
    nakshatra: "नक्षत्र",
    // Messaging quota
    daily_limit_reached: "आज की संदेश सीमा समाप्त।",
    try_again_at: "{time} के बाद फिर से भेजें।",
    send_message: "संदेश भेजें",
    premium_only: "केवल प्रीमियम सदस्यों के लिए",
    // Payment
    scan_qr_to_pay: "QR स्कैन करें और ₹499 भुगतान करें",
    payment_pending_approval: "भुगतान स्वीकृति प्रतीक्षारत है",
    payment_approved_premium: "भुगतान स्वीकृत — आप अब प्रीमियम सदस्य हैं!",
    // Admin labels
    sms_api_settings: "SMS API सेटिंग्स",
    test_sms: "SMS परीक्षण",
    chatbot_conversations: "चैटबॉट वार्तालाप",
    approve_payment: "भुगतान स्वीकृत करें",
    reject_label: "अस्वीकृत करें",
    chatbot_sessions: "चैटबॉट वार्तालाप",
    // Advertisements
    adManagement: "विज्ञापन प्रबंधन",
    addNewAd: "नया विज्ञापन जोड़ें",
    editAd: "विज्ञापन संपादित करें",
    deleteAd: "विज्ञापन हटाएं",
    companyName: "कंपनी का नाम",
    adText: "विज्ञापन पाठ",
    contactNumber: "संपर्क नंबर",
    websiteLink: "वेबसाइट लिंक",
    adImage: "विज्ञापन छवि URL",
    startDate: "प्रारंभ तिथि",
    endDate: "समाप्ति तिथि",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    expired: "समाप्त",
    adType: "विज्ञापन प्रकार",
    imageOnly: "केवल छवि",
    textOnly: "केवल पाठ",
    imageAndText: "छवि + पाठ",
    views: "दृश्य",
    clicks: "क्लिक",
    noAds: "कोई विज्ञापन नहीं",
    adCreated: "विज्ञापन बनाया गया",
    adUpdated: "विज्ञापन अपडेट किया गया",
    adDeleted: "विज्ञापन हटाया गया",
    adActivated: "विज्ञापन सक्रिय किया गया",
    adDeactivated: "विज्ञापन निष्क्रिय किया गया",
    // New keys
    birthTimeHelper: "सटीक कुंडली मिलन के लिए जन्म समय आवश्यक है",
    otpServiceUnavailable: "OTP सेवा उपलब्ध नहीं, लेकिन लॉगिन जारी है",
    passwordChanged: "Admin पासवर्ड सफलतापूर्वक बदल गया",
    logoUpdated: "Logo अपडेट हुआ — बदलाव रीलोड के बाद दिखेगा",
    perYear: "प्रति वर्ष",
  },

  english: {
    // Navigation
    home: "Home",
    profiles: "Profiles",
    matches: "Matches",
    plans: "Plans",
    stories: "Stories",
    adminPanel: "Admin Panel",
    login: "Login",
    logout: "Logout",
    messages: "Messages",
    search: "Search",
    register: "Register",
    back: "Back",
    joinNow: "Join ₹499",
    appName: "Vivah Setu",
    appTagline: "Trusted matrimony platform for the Digambar Jain community",
    community: "Digambar Jain Community",
    langLabel: "EN",

    // Auth/OTP
    mobileLogin: "Mobile Login",
    loginTitle: "Vivah Setu",
    loginSubtitle: "Trusted matrimony platform for the Digambar Jain community",
    otpTitle: "Verify OTP",
    otpSendSuccess: "OTP sent successfully",
    otpSentTo: "OTP sent to:",
    otpSendFailed: "OTP delivery failed — please try again",
    rateLimitMsg: "Too many attempts. Please wait 1 hour.",
    resending: "Resending...",
    resendOtp: "Resend OTP",
    changeNumber: "Change number",
    enterMobile: "Enter mobile number",
    enterOtp: "Enter OTP",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    invalidMobile: "Invalid mobile number",
    invalidOtp: "Invalid OTP",

    // Registration steps
    step1Title: "Personal Information",
    step2Title: "Community Info",
    step3Title: "Verification",
    step4Title: "Education & Career",
    step5Title: "Family Details",
    step6Title: "Partner Preferences",
    step7Title: "Photo & Profile",
    step1: "Personal Information",
    step2: "Education & Occupation",
    step3: "Family Details",
    step4: "Partner Preferences",
    step5: "Photo Upload",
    step6: "Profile Preview",
    step7: "Membership",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    stepOf: "of",

    // Profile fields
    firstName: "First Name",
    lastName: "Last Name",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    mobile: "Mobile",
    city: "City",
    state: "State",
    country: "Country",
    height: "Height",
    weight: "Weight",
    complexion: "Complexion",
    education: "Education",
    occupation: "Occupation",
    income: "Annual Income",
    employerName: "Employer Name",
    fatherName: "Father's Name",
    motherName: "Mother's Name",
    siblings: "Siblings",
    familyType: "Family Type",
    familyStatus: "Family Status",
    upjati: "Sub-community (optional)",
    partnerMinAge: "Partner Min Age",
    partnerMaxAge: "Partner Max Age",
    partnerCity: "Partner City",
    partnerEducation: "Partner Education",
    partnerOccupation: "Partner Occupation",
    uploadPhoto: "Upload Photo",
    photoInstructions: "JPEG/PNG, max 5MB",
    photoPreview: "Photo Preview",
    profilePreview: "Profile Preview",
    submitProfile: "Submit Profile",
    editProfile: "Edit Profile",
    male: "Male",
    female: "Female",
    employed: "Employed",
    selfEmployed: "Self-Employed",
    business: "Business",
    student: "Student",
    other: "Other",
    nuclear: "Nuclear Family",
    joint: "Joint Family",

    // Profile actions
    age: "Age",
    yearsOld: "years old",
    about: "About Me",
    contactInfo: "Contact Info",
    profileCompleteness: "Profile Completeness",
    viewProfile: "View Profile",
    sendMessage: "Send Message",
    expressInterest: "Express Interest",
    shortlist: "Shortlist",
    report: "Report",
    memberSince: "Member Since",
    lastSeen: "Last Seen",
    premiumMember: "Premium Member",
    freeMember: "Member",
    profileStatus: "Profile Status",
    pendingApproval: "Pending Approval",

    // Payment/Plans
    membershipPlans: "Membership Plans",
    freePlan: "Premium Plan",
    premiumPlan: "Premium Plan",
    upgradeNow: "Upgrade Now",
    currentPlan: "Current Plan",
    planPrice: "Price",
    planDuration: "Duration",
    planBenefits: "Benefits",
    paymentInstructions:
      "Scan the UPI QR or use the UPI ID and upload a screenshot",
    upiId: "UPI ID",
    scanAndPay: "Scan and pay ₹499",
    downloadQr: "Download QR Code",
    uploadScreenshot: "Upload Screenshot",
    screenshotUploaded: "Screenshot Uploaded",
    paymentPending: "Payment approval pending",
    paymentApproved: "Payment approved!",
    paymentRejected: "Payment rejected",
    paymentNote: "Admin will approve within 24 hours",
    payNow: "Pay Now",
    orPayUpi: "Or use UPI ID",
    paymentAmount: "Payment Amount",
    upiRef: "UPI Reference Number",

    // Messaging
    noConversations: "No conversations yet",
    conversationWith: "Conversation with",
    loadingMessages: "Loading messages...",
    dailyLimitReached: "Daily message limit reached!",
    premiumOnly: "For premium members only",
    messageSent: "Message sent",
    messageError: "Failed to send message",
    upgradeForUnlimited: "Upgrade for unlimited messages",
    send: "Send",
    messagesRemaining: "messages remaining",
    upgradePrompt: "Upgrade to Premium for unlimited messages",
    noMessages: "No messages yet",
    typeMessage: "Type a message...",

    // Success Stories
    successStories: "Success Stories",
    ourCouples: "Our Couples",
    addStory: "Add Story",
    noStories: "No stories yet",
    storyTitle: "Title",
    storyContent: "Success Story",
    coupleNames: "Couple Names",
    marriageDate: "Marriage Date",
    shareYourStory: "Share Your Story",
    readMore: "Read More",
    viewAll: "View All",

    // Search/Browse
    searchProfiles: "Search Profiles",
    filterBy: "Filter By",
    ageRange: "Age Range",
    minAge: "Min Age",
    maxAge: "Max Age",
    genderFilter: "Gender",
    cityFilter: "City",
    educationFilter: "Education",
    applyFilters: "Apply Filters",
    clearFilters: "Clear Filters",
    noResultsFound: "No results found",
    showingResults: "Showing results",
    sortBy: "Sort By",
    newest: "Newest",
    oldest: "Oldest",
    relevance: "Relevance",
    allProfiles: "All Profiles",
    featuredProfiles: "Featured Profiles",
    newProfiles: "New Profiles",
    onlineNow: "Online Now",

    // Admin
    adminDashboard: "Admin Dashboard",
    manageMembers: "Manage Members",
    managePayments: "Manage Payments",
    manageStories: "Manage Stories",
    moderatePhotos: "Moderate Photos",
    manageMessages: "Manage Messages",
    adminSettings: "Admin Settings",
    totalMembers: "Total Members",
    pendingApprovals: "Pending Approvals",
    paidMembers: "Paid Members",
    activeToday: "Active Today",
    approveProfile: "Approve Profile",
    rejectProfile: "Reject Profile",
    deleteProfile: "Delete Profile",
    viewDetails: "View Details",
    approvePayment: "Approve Payment",
    rejectPayment: "Reject Payment",
    paymentDetails: "Payment Details",
    transactionId: "Transaction ID",
    approvePhoto: "Approve Photo",
    rejectPhoto: "Reject Photo",
    photoModeration: "Photo Moderation",
    deleteMessage: "Delete Message",
    messageManagement: "Message Management",
    smsProvider: "SMS Provider",
    smsApiKey: "API Key",
    smsSenderName: "Sender Name",
    enableSms: "Enable SMS",
    testSms: "Test SMS",
    saveSmsConfig: "Save SMS Config",
    smsConfigSaved: "SMS settings saved",
    adminLogin: "Admin Login",
    adminPassword: "Admin Password",
    adminLogout: "Admin Logout",
    exportData: "Export Data",
    importData: "Import Data",
    refreshData: "Refresh Data",

    // Admin tabs
    dashboard: "Dashboard",
    members: "Members",
    payments: "Payments",
    adminStories: "Success Stories",
    photos: "Photos",
    adminMessages: "Messages",
    settings: "Settings",

    // Photo moderation
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",

    // General UI
    loading: "Loading...",
    error: "An error occurred",
    success: "Success",
    warning: "Warning",
    info: "Info",
    noResults: "No results found",
    tryAgain: "Try Again",
    goBack: "Go Back",
    goHome: "Go Home",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    confirm: "Confirm",
    close: "Close",
    yes: "Yes",
    no: "No",
    ok: "OK",
    required: "This field is required",
    optional: "Optional",
    reset: "Reset",
    showMore: "Show More",
    showLess: "Show Less",
    seeMore: "See More",
    fileTooLarge: "File must not exceed 5MB",
    invalidFileType: "Only JPEG/PNG images are accepted",
    uploadFailed: "Upload failed",
    uploadSuccess: "Upload successful",
    copiedToClipboard: "Copied to clipboard",
    shareLink: "Share Link",
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    goodbye: "Goodbye",
    premiumBadge: "Premium",
    verifiedBadge: "Verified",
    newBadge: "New",
    marqueeText:
      "This app is exclusively for brides and grooms of the Digambar Jain community",
    footerCopyright: "© Vivah Setu. All rights reserved.",
    quickLinks: "Quick Links",
    browseProfles: "Browse Profiles",
    advancedSearch: "Advanced Search",
    todaysMatches: "Today's Matches",
    successStoriesLink: "Success Stories",
    joinPremium: "Join Premium",
    alwaysFree: "Join for ₹499",
    // Chatbot
    chatbot_title: "Vivah Setu Assistant",
    chatbot_placeholder: "Type a message...",
    chatbot_send: "Send",
    chatbot_greeting: "Namaste! I am Vivah Setu Assistant. Ready to help!",
    // Kundali Milan
    kundali_title: "🔮 Kundali Milan Result",
    kundali_btn: "Kundali Milan",
    kundali_varna: "Varna",
    kundali_vashya: "Vashya",
    kundali_tara: "Tara",
    kundali_yoni: "Yoni",
    kundali_graha_maitri: "Graha Maitri",
    kundali_gana: "Gana",
    kundali_bhakoot: "Bhakoot",
    kundali_nadi: "Nadi",
    kundali_total: "Total Score",
    kundali_score_of: "out of 36",
    kundali_uttam: "Excellent 💚",
    kundali_madhyam: "Average 🟡",
    kundali_ashubh: "Inauspicious 🔴",
    kundali_rashi: "Rashi",
    kundali_charan: "Charan",
    kundali_precise_note:
      "Calculation uses precise astronomical data (birth time included)",
    kundali_approx_note: "Approximate calculation (birth time not available)",
    // Birth details
    birth_time: "Birth Time (optional)",
    birth_place: "Birth Place (optional)",
    nakshatra: "Nakshatra",
    // Messaging quota
    daily_limit_reached: "Daily message limit reached.",
    try_again_at: "Send messages again after {time}.",
    send_message: "Send Message",
    premium_only: "Premium members only",
    // Payment
    scan_qr_to_pay: "Scan QR to pay ₹499",
    payment_pending_approval: "Payment approval pending",
    payment_approved_premium:
      "Payment approved — you are now a Premium member!",
    // Admin labels
    sms_api_settings: "SMS API Settings",
    test_sms: "Test SMS",
    chatbot_conversations: "Chatbot Conversations",
    approve_payment: "Approve Payment",
    reject_label: "Reject",
    chatbot_sessions: "Chatbot Conversations",
    // Advertisements
    adManagement: "Advertisement Management",
    addNewAd: "Add New Ad",
    editAd: "Edit Ad",
    deleteAd: "Delete Ad",
    companyName: "Company Name",
    adText: "Ad Text",
    contactNumber: "Contact Number",
    websiteLink: "Website Link",
    adImage: "Ad Image URL",
    startDate: "Start Date",
    endDate: "End Date",
    active: "Active",
    inactive: "Inactive",
    expired: "Expired",
    adType: "Ad Type",
    imageOnly: "Image Only",
    textOnly: "Text Only",
    imageAndText: "Image + Text",
    views: "Views",
    clicks: "Clicks",
    noAds: "No advertisements yet",
    adCreated: "Advertisement created",
    adUpdated: "Advertisement updated",
    adDeleted: "Advertisement deleted",
    adActivated: "Advertisement activated",
    adDeactivated: "Advertisement deactivated",
    // New keys
    birthTimeHelper: "Birth time is essential for accurate Kundali matching",
    otpServiceUnavailable: "OTP service unavailable, but login is proceeding",
    passwordChanged: "Admin password changed successfully",
    logoUpdated: "Logo updated — changes visible after reload",
    perYear: "per year",
  },
};
